const SOURCES = [
  {
    id: "mit-senseable",
    name: "MIT Senseable City Lab",
    type: "lab",
    region: "美国",
    url: "https://senseable.mit.edu/",
    latestUrl: "https://senseable.mit.edu/news/",
    folder: "城市科学实验室",
    tags: ["城市感知", "数据可视化", "城市科学"],
    description: "MIT 城市数据与感知计算研究实验室，关注城市活动、移动性、环境与实时数据。",
    includeReason: "全球代表性城市科学实验室。"
  },
  {
    id: "mit-city-science",
    name: "MIT City Science",
    type: "lab",
    region: "美国",
    url: "https://www.media.mit.edu/groups/city-science/overview/",
    latestUrl: "https://www.media.mit.edu/groups/city-science/projects/",
    folder: "城市科学实验室",
    tags: ["城市科学", "Media Lab", "未来城市"],
    description: "MIT Media Lab 城市科学小组，聚焦城市系统、计算设计与新型城市生活方式。",
    includeReason: "收藏夹中明确标注为 City Science。"
  },
  {
    id: "mit-city-form",
    name: "MIT City Form Lab",
    type: "lab",
    region: "美国",
    url: "http://cityform.mit.edu/projects",
    latestUrl: "http://cityform.mit.edu/projects",
    folder: "城市科学实验室",
    tags: ["城市形态", "网络分析", "空间模型"],
    description: "关注城市形态、街道网络、可达性和城市空间结构的研究平台。",
    includeReason: "城市形态与空间分析研究来源。"
  },
  {
    id: "harvard-maps",
    name: "Harvard MaP+S Group",
    type: "lab",
    region: "美国",
    url: "https://research.gsd.harvard.edu/maps/about-1/",
    latestUrl: "https://research.gsd.harvard.edu/maps/projects/",
    folder: "城市科学实验室",
    tags: ["空间数据", "建成环境", "地图"],
    description: "Harvard GSD 的建模、分析、原型和系统研究组。",
    includeReason: "城市空间数据与建成环境研究相关。"
  },
  {
    id: "harvard-real",
    name: "Harvard REAL",
    type: "lab",
    region: "美国",
    url: "https://research.gsd.harvard.edu/real/",
    latestUrl: "https://research.gsd.harvard.edu/real/projects/",
    folder: "城市科学实验室",
    tags: ["房地产", "城市经济", "城市数据"],
    description: "Harvard GSD Real Estate and the Built Environment Lab。",
    includeReason: "建成环境和城市经济研究实验室。"
  },
  {
    id: "eth-fcl",
    name: "Future Cities Laboratory",
    type: "lab",
    region: "新加坡/瑞士",
    url: "https://fcl.ethz.ch/",
    latestUrl: "https://fcl.ethz.ch/news.html",
    folder: "城市科学实验室",
    tags: ["未来城市", "可持续城市", "跨学科"],
    description: "ETH Zurich 与新加坡相关研究平台，聚焦未来城市与可持续建成环境。",
    includeReason: "全球领先未来城市研究平台。"
  },
  {
    id: "ucl-casa",
    name: "UCL CASA",
    type: "lab",
    region: "英国",
    url: "https://www.ucl.ac.uk/bartlett/casa/bartlett-centre-advanced-spatial-analysis",
    latestUrl: "https://www.ucl.ac.uk/bartlett/casa/news",
    folder: "城市科学实验室",
    tags: ["空间分析", "城市模型", "数据科学"],
    description: "UCL Bartlett Centre for Advanced Spatial Analysis，城市空间分析代表机构。",
    includeReason: "收藏夹中明确为高级空间分析中心。"
  },
  {
    id: "ual-singapore",
    name: "Urban Analytics Lab Singapore",
    type: "lab",
    region: "新加坡",
    url: "https://ual.sg/",
    latestUrl: "https://ual.sg/research/",
    folder: "城市科学实验室",
    tags: ["城市分析", "亚洲城市", "计算城市"],
    description: "新加坡城市分析实验室，关注城市数据、计算方法与亚洲城市问题。",
    includeReason: "收藏夹中明确为 Urban Analytics Lab。"
  },
  {
    id: "beijing-city-lab",
    name: "Beijing City Lab",
    type: "lab",
    region: "中国",
    url: "https://www.beijingcitylab.com/",
    latestUrl: "https://www.beijingcitylab.com/publications/",
    folder: "城市科学实验室",
    tags: ["中国城市", "开放数据", "城市模型"],
    description: "面向中国城市研究的开放数据、论文与城市分析平台。",
    includeReason: "城市实验室与研究成果长期更新。"
  },
  {
    id: "hku-dil",
    name: "HKU Data Intelligence Lab",
    type: "lab",
    region: "中国香港",
    url: "https://sites.google.com/view/chaoh/group-join-us",
    latestUrl: "https://sites.google.com/view/chaoh/publications",
    folder: "城市科学实验室",
    tags: ["智慧城市", "数据智能", "城市分析"],
    description: "香港大学智慧城市与数据智能相关研究团队。",
    includeReason: "收藏夹标注为 HKU 智慧城市实验室。"
  },
  {
    id: "tudelft-uds",
    name: "TU Delft Urban Data Science",
    type: "lab",
    region: "荷兰",
    url: "https://www.tudelft.nl/en/architecture-and-the-built-environment/about-the-faculty/departments/urbanism/organisation/sections/urban-data-science/",
    latestUrl: "https://www.tudelft.nl/en/architecture-and-the-built-environment/about-the-faculty/departments/urbanism/organisation/sections/urban-data-science/",
    folder: "城市科学实验室",
    tags: ["城市数据科学", "城市规划", "计算方法"],
    description: "代尔夫特理工城市数据科学方向，连接城市规划与计算方法。",
    includeReason: "收藏夹中明确为城市数据科学实验室。"
  },
  {
    id: "tudelft-urban-studies",
    name: "TU Delft Urban Studies",
    type: "lab",
    region: "荷兰",
    url: "https://www.tudelft.nl/en/architecture-and-the-built-environment/about-the-faculty/departments/urbanism/organisation/sections/urban-studies",
    latestUrl: "https://www.tudelft.nl/en/architecture-and-the-built-environment/about-the-faculty/departments/urbanism/organisation/sections/urban-studies",
    folder: "城市科学实验室",
    tags: ["城市研究", "规划理论", "城市化"],
    description: "TU Delft 城市研究方向，关注城市化、规划和空间转型。",
    includeReason: "城市研究学术机构。"
  },
  {
    id: "ams-institute",
    name: "AMS Institute",
    type: "institution",
    region: "荷兰",
    url: "https://www.ams-institute.org/",
    latestUrl: "https://www.ams-institute.org/news/",
    folder: "城市科学实验室",
    tags: ["城市创新", "可持续城市", "应用研究"],
    description: "Amsterdam Institute for Advanced Metropolitan Solutions，连接城市研究与应用创新。",
    includeReason: "收藏夹中阿姆斯特丹城市研究机构。"
  },
  {
    id: "shanghai-global-city",
    name: "上海全球城市研究院",
    type: "institution",
    region: "中国",
    url: "http://sigc.shnu.edu.cn/main.htm",
    latestUrl: "http://sigc.shnu.edu.cn/main.htm",
    folder: "城市研究机构",
    tags: ["全球城市", "长三角", "城市网络"],
    description: "围绕全球城市、城市网络和区域一体化开展研究。",
    includeReason: "收藏夹中明确为城市研究院。"
  },
  {
    id: "wri-china",
    name: "WRI China",
    type: "institution",
    region: "中国/全球",
    url: "https://wri.org.cn/",
    latestUrl: "https://wri.org.cn/insights",
    folder: "城市研究机构",
    tags: ["可持续城市", "气候", "交通"],
    description: "世界资源研究所中国办公室，长期发布城市、交通、气候与可持续发展研究。",
    includeReason: "可持续城市与政策研究机构。"
  },
  {
    id: "nacto",
    name: "NACTO",
    type: "institution",
    region: "美国/全球",
    url: "https://nacto.org/publication/transit-street-design-guide/",
    latestUrl: "https://nacto.org/publications/",
    feed: "https://nacto.org/feed/",
    folder: "城市研究机构",
    tags: ["街道设计", "交通", "公共空间"],
    description: "城市交通官员协会，发布街道设计、公交街道和城市交通指南。",
    includeReason: "城市交通与街道研究实践指南来源。"
  },
  {
    id: "itdp-china",
    name: "ITDP China",
    type: "institution",
    region: "中国/全球",
    url: "http://www.itdp-china.org/",
    latestUrl: "http://www.itdp-china.org/",
    folder: "城市研究机构",
    tags: ["可持续交通", "TOD", "低碳城市"],
    description: "交通与发展政策研究所中国，关注可持续交通、公交、步行与低碳城市。",
    includeReason: "城市交通政策研究机构。"
  },
  {
    id: "pps",
    name: "Project for Public Spaces",
    type: "institution",
    region: "美国/全球",
    url: "https://www.pps.org/our-team",
    latestUrl: "https://www.pps.org/articles",
    folder: "城市研究机构",
    tags: ["公共空间", "场所营造", "社区"],
    description: "公共空间与场所营造非营利研究和实践组织。",
    includeReason: "收藏夹中城市公共空间非盈利研究组织。"
  },
  {
    id: "china-stc",
    name: "宇恒可持续交通研究中心",
    type: "institution",
    region: "中国",
    url: "http://www.chinastc.org/gywm",
    latestUrl: "http://www.chinastc.org/",
    folder: "城市研究机构",
    tags: ["可持续交通", "城市交通", "低碳"],
    description: "关注可持续交通、城市交通政策与低碳出行的研究中心。",
    includeReason: "收藏夹中标注为可持续交通研究中心。"
  },
  {
    id: "src-street",
    name: "SRC 城市街景设计研究中心",
    type: "institution",
    region: "中国",
    url: "http://www.streetsrc.com/",
    latestUrl: "http://www.streetsrc.com/",
    folder: "城市研究机构",
    tags: ["街景", "街道设计", "城市品质"],
    description: "围绕城市街景、街道空间和设计研究的机构。",
    includeReason: "城市街景研究相关。"
  },
  {
    id: "ura-singapore",
    name: "URA Singapore Publications",
    type: "institution",
    region: "新加坡",
    url: "https://www.ura.gov.sg/Corporate/Resources/Publications",
    latestUrl: "https://www.ura.gov.sg/Corporate/Resources/Publications",
    folder: "城市研究机构",
    tags: ["城市规划", "新加坡", "政策出版"],
    description: "新加坡市区重建局出版物入口，可跟踪城市规划政策和研究资料。",
    includeReason: "官方城市规划出版物来源。"
  },
  {
    id: "nyu-cusp",
    name: "NYU Center for Urban Science and Progress",
    type: "institution",
    region: "美国",
    url: "https://cusp.nyu.edu/",
    latestUrl: "https://cusp.nyu.edu/research/",
    folder: "全球城市研究机构",
    tags: ["城市科学", "城市信息学", "数据科学"],
    description: "纽约大学城市科学与进步中心，围绕城市信息学、城市数据与应用城市科学开展教学和研究。",
    includeReason: "全球城市科学与城市信息学代表性研究中心。"
  },
  {
    id: "nyu-marron",
    name: "NYU Marron Institute of Urban Management",
    type: "institution",
    region: "美国",
    url: "https://marroninstitute.nyu.edu/",
    latestUrl: "https://marroninstitute.nyu.edu/blog",
    folder: "全球城市研究机构",
    tags: ["城市管理", "应用研究", "政策"],
    description: "纽约大学城市管理研究院，关注城市治理、交通与土地利用、健康环境和城市扩张等应用研究。",
    includeReason: "应用城市研究和城市政策项目长期更新。"
  },
  {
    id: "penn-iur",
    name: "Penn Institute for Urban Research",
    type: "institution",
    region: "美国",
    url: "https://penniur.upenn.edu/",
    latestUrl: "https://penniur.upenn.edu/news/",
    folder: "全球城市研究机构",
    tags: ["城市研究", "可持续城市", "政策"],
    description: "宾夕法尼亚大学跨学科城市研究机构，关注城市发展、包容性和可持续城市议题。",
    includeReason: "高校城市研究中心和全球城市研究网络入口。"
  },
  {
    id: "uchicago-mansueto",
    name: "Mansueto Institute for Urban Innovation",
    type: "institution",
    region: "美国",
    url: "https://miurban.uchicago.edu/",
    latestUrl: "https://miurban.uchicago.edu/news/",
    folder: "全球城市研究机构",
    tags: ["城市创新", "城市政策", "研究资助"],
    description: "芝加哥大学城市创新研究平台，支持城市议题研究、训练、项目和公共活动。",
    includeReason: "城市创新与城市政策研究来源。"
  },
  {
    id: "nyu-urban-systems-lab",
    name: "Urban Systems Lab",
    type: "lab",
    region: "美国/全球",
    url: "https://urbansystemslab.com/",
    latestUrl: "https://urbansystemslab.com/news",
    folder: "城市科学实验室",
    tags: ["城市韧性", "气候风险", "自然基解决方案"],
    description: "面向宜居城市的城市系统实验室，研究城市韧性、气候适应和社会生态系统。",
    includeReason: "全球城市韧性和气候适应研究实验室。"
  },
  {
    id: "columbia-csr",
    name: "Columbia Center for Spatial Research",
    type: "institution",
    region: "美国",
    url: "https://c4sr.columbia.edu/",
    latestUrl: "https://c4sr.columbia.edu/news",
    folder: "全球城市研究机构",
    tags: ["空间研究", "制图", "数据可视化"],
    description: "哥伦比亚大学空间研究中心，连接建筑、城市主义、人文和数据科学。",
    includeReason: "空间数据、城市制图和批判性城市研究平台。"
  },
  {
    id: "bari",
    name: "Boston Area Research Initiative",
    type: "institution",
    region: "美国",
    url: "https://cssh.northeastern.edu/bari/",
    latestUrl: "https://cssh.northeastern.edu/bari/news/",
    folder: "全球城市研究机构",
    tags: ["城市数据", "社区", "城市治理"],
    description: "波士顿区域研究计划，使用城市数据连接社区、政策和学术研究。",
    includeReason: "城市数据治理和城市社会研究案例库。"
  },
  {
    id: "cmu-metro21",
    name: "Metro21: Smart Cities Institute",
    type: "institution",
    region: "美国",
    url: "https://www.cmu.edu/metro21/",
    latestUrl: "https://www.cmu.edu/metro21/news/",
    folder: "全球城市研究机构",
    tags: ["智慧城市", "交通", "社区技术"],
    description: "卡内基梅隆大学智慧城市研究与实施中心，连接技术研究、社区合作和政策落地。",
    includeReason: "智慧城市和城市技术应用研究来源。"
  },
  {
    id: "lse-cities",
    name: "LSE Cities",
    type: "institution",
    region: "英国/全球",
    url: "https://www.lse.ac.uk/cities",
    latestUrl: "https://www.lse.ac.uk/cities/news",
    folder: "全球城市研究机构",
    tags: ["全球城市", "城市治理", "城市可持续"],
    description: "伦敦政治经济学院国际城市研究中心，研究 21 世纪城市的社会、空间和环境复杂性。",
    includeReason: "全球城市治理、城市可持续和 Urban Age 研究来源。"
  },
  {
    id: "ubdc",
    name: "Urban Big Data Centre",
    type: "institution",
    region: "英国",
    url: "https://www.ubdc.ac.uk/",
    latestUrl: "https://www.ubdc.ac.uk/news-events/",
    folder: "全球城市研究机构",
    tags: ["城市大数据", "数据服务", "城市分析"],
    description: "格拉斯哥大学城市大数据中心，提供城市智能数据服务、研究主题和数据目录。",
    includeReason: "城市大数据、交通、住房、劳动力和环境数据研究平台。"
  },
  {
    id: "hcu-city-science-lab",
    name: "CityScienceLab Hamburg",
    type: "lab",
    region: "德国",
    url: "https://www.hcu-hamburg.de/en/research/citysciencelab",
    latestUrl: "https://www.hcu-hamburg.de/en/research/citysciencelab/news",
    folder: "城市科学实验室",
    tags: ["城市科学", "数字城市", "城市模拟"],
    description: "汉堡 HafenCity University 与 MIT Media Lab 相关的城市科学实验室，关注数字化背景下的城市挑战。",
    includeReason: "欧洲城市科学、城市模拟和数字城市研究来源。"
  },
  {
    id: "school-of-cities",
    name: "University of Toronto School of Cities",
    type: "institution",
    region: "加拿大",
    url: "https://schoolofcities.utoronto.ca/",
    latestUrl: "https://schoolofcities.utoronto.ca/research-publications/",
    folder: "全球城市研究机构",
    tags: ["城市研究", "城市数据", "跨学科"],
    description: "多伦多大学城市学院，围绕城市研究、教育和参与建立跨学科平台。",
    includeReason: "北美跨学科城市研究和城市数据项目来源。"
  },
  {
    id: "african-centre-cities",
    name: "African Centre for Cities",
    type: "institution",
    region: "南非/非洲",
    url: "https://www.africancentreforcities.net/",
    latestUrl: "https://www.africancentreforcities.net/research/",
    feed: "https://www.africancentreforcities.net/feed/",
    folder: "全球城市研究机构",
    tags: ["非洲城市", "全球南方", "可持续城市"],
    description: "开普敦大学非洲城市中心，开展全球南方视角下的应用城市研究、教学和公共传播。",
    includeReason: "非洲城市研究和全球南方城市议题核心来源。"
  },
  {
    id: "iihs",
    name: "Indian Institute for Human Settlements",
    type: "institution",
    region: "印度",
    url: "https://iihs.co.in/",
    latestUrl: "https://iihs.co.in/research/",
    folder: "全球城市研究机构",
    tags: ["人居环境", "城市化", "南亚城市"],
    description: "印度人居环境研究与教育机构，覆盖城市化研究、实验室、实践项目和 Urbanisation 期刊。",
    includeReason: "南亚城市化、人居环境和城市政策研究来源。"
  },
  {
    id: "cedeus",
    name: "CEDEUS",
    type: "institution",
    region: "智利/拉美",
    url: "https://www.cedeus.cl/",
    latestUrl: "https://www.cedeus.cl/noticias/",
    folder: "全球城市研究机构",
    tags: ["可持续城市", "拉美城市", "城市观测"],
    description: "智利可持续城市发展中心，联合高校开展城市可持续、城市观测和政策转化。",
    includeReason: "拉美可持续城市研究和观测平台。"
  },
  {
    id: "observatorio-metropoles",
    name: "Observatório das Metrópoles",
    type: "institution",
    region: "巴西",
    url: "https://www.observatoriodasmetropoles.net.br/",
    latestUrl: "https://www.observatoriodasmetropoles.net.br/noticias/",
    feed: "https://www.observatoriodasmetropoles.net.br/feed/",
    folder: "全球城市研究机构",
    tags: ["都市圈", "城市不平等", "巴西城市"],
    description: "巴西都市圈观测研究网络，覆盖大都市治理、社会空间不平等和城市公共政策。",
    includeReason: "拉美都市圈研究和南南合作资料入口。"
  },
  {
    id: "polyu-scri",
    name: "PolyU Smart Cities Research Institute",
    type: "institution",
    region: "中国香港",
    url: "https://www.polyu.edu.hk/scri/",
    latestUrl: "https://www.polyu.edu.hk/scri/news-and-events/news/",
    folder: "全球城市研究机构",
    tags: ["智慧城市", "城市信息学", "大湾区"],
    description: "香港理工大学智慧城市研究院，聚焦城市信息学、智慧交通、智慧环境、治理和经济。",
    includeReason: "亚洲智慧城市与城市信息学研究平台。"
  },
  {
    id: "nature-cities",
    name: "Nature Cities",
    type: "journal",
    region: "全球",
    url: "https://www.nature.com/natcities/",
    latestUrl: "https://www.nature.com/natcities/research-articles",
    folder: "城市研究期刊",
    tags: ["综合城市研究", "Nature", "论文"],
    description: "Nature Portfolio 城市研究期刊，覆盖城市科学、城市政策与可持续城市议题。",
    includeReason: "收藏夹中明确为自然城市期刊。"
  },
  {
    id: "cities",
    name: "Cities",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/cities",
    latestUrl: "https://www.sciencedirect.com/journal/cities/issues",
    folder: "城市研究期刊",
    issn: ["0264-2751"],
    tags: ["城市研究", "城市政策", "论文"],
    description: "Elsevier 城市研究期刊，关注城市政策、城市化与空间发展。",
    includeReason: "核心城市研究期刊。"
  },
  {
    id: "ceus",
    name: "Computers, Environment and Urban Systems",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/computers-environment-and-urban-systems",
    latestUrl: "https://www.sciencedirect.com/journal/computers-environment-and-urban-systems/issues",
    folder: "城市研究期刊",
    issn: ["0198-9715"],
    tags: ["城市系统", "计算方法", "GIS"],
    description: "城市系统、计算、GIS、环境与城市数据方法相关期刊。",
    includeReason: "计算城市研究关键期刊。"
  },
  {
    id: "sustainable-cities",
    name: "Sustainable Cities and Society",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/sustainable-cities-and-society",
    latestUrl: "https://www.sciencedirect.com/journal/sustainable-cities-and-society/issues",
    folder: "城市研究期刊",
    issn: ["2210-6707"],
    tags: ["可持续城市", "社会", "论文"],
    description: "关注可持续城市、气候、能源、社会与建成环境的期刊。",
    includeReason: "可持续城市研究核心期刊。"
  },
  {
    id: "landscape-urban-planning",
    name: "Landscape and Urban Planning",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/landscape-and-urban-planning",
    latestUrl: "https://www.sciencedirect.com/journal/landscape-and-urban-planning/issues",
    folder: "城市研究期刊",
    issn: ["0169-2046"],
    tags: ["景观", "城市规划", "生态"],
    description: "景观、城市规划、生态系统服务和空间规划研究期刊。",
    includeReason: "城市与景观规划核心期刊。"
  },
  {
    id: "epb",
    name: "Environment and Planning B",
    type: "journal",
    region: "全球",
    url: "https://journals.sagepub.com/home/epb",
    latestUrl: "https://journals.sagepub.com/toc/EPB/current",
    folder: "城市研究期刊",
    issn: ["2399-8083", "2399-8091"],
    tags: ["城市分析", "城市科学", "空间计算"],
    description: "Environment and Planning B: Urban Analytics and City Science。",
    includeReason: "城市分析与城市科学代表期刊。"
  },
  {
    id: "urban-research-practice",
    name: "Urban Research & Practice",
    type: "journal",
    region: "全球",
    url: "https://www.tandfonline.com/toc/rurp20/current",
    latestUrl: "https://www.tandfonline.com/toc/rurp20/current",
    folder: "城市研究期刊",
    issn: ["1753-5069", "1753-5077"],
    tags: ["城市研究", "实践", "政策"],
    description: "连接城市研究、政策与实践的 Taylor & Francis 期刊。",
    includeReason: "收藏夹中明确为 Urban Research & Practice。"
  },
  {
    id: "city-community",
    name: "City & Community",
    type: "journal",
    region: "全球",
    url: "https://onlinelibrary.wiley.com/journal/15406040",
    latestUrl: "https://onlinelibrary.wiley.com/journal/15406040",
    folder: "城市研究期刊",
    issn: ["1540-6040", "1535-6841"],
    tags: ["城市社会学", "社区", "论文"],
    description: "城市社会学、社区和城市社会研究相关期刊。",
    includeReason: "收藏夹中城市与社区期刊。"
  },
  {
    id: "arxiv-cs-cy",
    name: "arXiv Computer and Society",
    type: "journal",
    region: "全球",
    url: "https://arxiv.org/list/cs.CY/recent?skip=0&show=25",
    latestUrl: "https://arxiv.org/list/cs.CY/recent?skip=0&show=25",
    folder: "城市研究期刊",
    feed: "https://export.arxiv.org/api/query?search_query=cat:cs.CY&start=0&max_results=8&sortBy=submittedDate&sortOrder=descending",
    feedKind: "atom",
    tags: ["预印本", "计算社会", "论文"],
    description: "计算机与社会方向预印本入口，可捕捉城市计算与社会技术研究信号。",
    includeReason: "可作为城市计算相关预印本监测入口。"
  },
  {
    id: "topos",
    name: "Topos Magazine",
    type: "journal",
    region: "全球",
    url: "https://toposmagazine.com/",
    latestUrl: "https://toposmagazine.com/",
    folder: "城市研究期刊",
    tags: ["景观", "城市主义", "杂志"],
    description: "景观建筑与城市主义国际评论平台。",
    includeReason: "收藏夹中城市与景观相关出版平台。"
  },
  {
    id: "scenario",
    name: "Scenario Journal",
    type: "journal",
    region: "全球",
    url: "https://scenariojournal.com/strategies/",
    latestUrl: "https://scenariojournal.com/",
    feed: "https://scenariojournal.com/feed/",
    folder: "城市研究期刊",
    tags: ["景观城市主义", "设计研究", "期刊"],
    description: "景观、生态与城市主义设计研究期刊。",
    includeReason: "收藏夹中设计研究期刊平台。"
  },
  {
    id: "springer-urban-studies",
    name: "Springer Urban Studies Series",
    type: "journal",
    region: "全球",
    url: "https://www.springer.com/series/16474/books",
    latestUrl: "https://www.springer.com/series/16474/books",
    folder: "城市研究期刊",
    tags: ["出版系列", "城市研究", "图书"],
    description: "Springer 城市研究系列图书入口。",
    includeReason: "虽非期刊，但属于城市研究出版系列，归入出版资源。"
  },
  {
    id: "urban-studies",
    name: "Urban Studies",
    type: "journal",
    region: "全球",
    url: "https://journals.sagepub.com/home/usj",
    latestUrl: "https://journals.sagepub.com/home/usj",
    folder: "城市研究期刊",
    issn: ["0042-0980", "1360-063X"],
    tags: ["综合城市研究", "城市理论", "社会科学"],
    description: "国际同行评审城市研究期刊，覆盖城市状况、城市区域变化和跨学科城市社会科学研究。",
    includeReason: "全球城市研究核心期刊。"
  },
  {
    id: "ijurr",
    name: "International Journal of Urban and Regional Research",
    type: "journal",
    region: "全球",
    url: "https://onlinelibrary.wiley.com/journal/14682427",
    latestUrl: "https://onlinelibrary.wiley.com/journal/14682427",
    folder: "城市研究期刊",
    issn: ["0309-1317", "1468-2427"],
    tags: ["城市研究", "区域研究", "城市理论"],
    description: "IJURR，关注城市与区域研究、城市理论、全球城市化和社会空间转型。",
    includeReason: "城市与区域研究国际核心期刊。"
  },
  {
    id: "journal-urban-affairs",
    name: "Journal of Urban Affairs",
    type: "journal",
    region: "全球",
    url: "https://www.tandfonline.com/journals/ujua20",
    latestUrl: "https://www.tandfonline.com/toc/ujua20/current",
    folder: "城市研究期刊",
    issn: ["0735-2166", "1467-9906"],
    tags: ["城市政策", "城市事务", "治理"],
    description: "Urban Affairs Association 相关期刊，关注城市政策、城市治理、社区和城市发展。",
    includeReason: "城市事务与城市政策研究期刊。"
  },
  {
    id: "urban-geography",
    name: "Urban Geography",
    type: "journal",
    region: "全球",
    url: "https://www.tandfonline.com/journals/rurb20",
    latestUrl: "https://www.tandfonline.com/toc/rurb20/current",
    folder: "城市研究期刊",
    issn: ["0272-3638", "1938-2847"],
    tags: ["城市地理", "空间不平等", "城市政策"],
    description: "城市地理学期刊，覆盖城市政策、规划、住房、贫困、族群和城市经济活动。",
    includeReason: "城市地理与城市空间研究核心来源。"
  },
  {
    id: "journal-urban-technology",
    name: "Journal of Urban Technology",
    type: "journal",
    region: "全球",
    url: "https://www.tandfonline.com/journals/cjut20",
    latestUrl: "https://www.tandfonline.com/toc/cjut20/current",
    folder: "城市研究期刊",
    issn: ["1063-0732", "1466-1853"],
    tags: ["城市技术", "智慧城市", "城市信息学"],
    description: "关注城市技术、智慧城市、信息基础设施和城市社会技术系统的期刊。",
    includeReason: "城市技术和智慧城市研究期刊。"
  },
  {
    id: "journal-urban-design",
    name: "Journal of Urban Design",
    type: "journal",
    region: "全球",
    url: "https://www.tandfonline.com/journals/cjud20",
    latestUrl: "https://www.tandfonline.com/toc/cjud20/current",
    folder: "城市研究期刊",
    issn: ["1357-4809", "1469-9664"],
    tags: ["城市设计", "建成环境", "公共空间"],
    description: "聚焦城市设计理论、方法、实践和建成环境品质的国际期刊。",
    includeReason: "城市设计研究核心期刊。"
  },
  {
    id: "journal-planning-education-research",
    name: "Journal of Planning Education and Research",
    type: "journal",
    region: "全球",
    url: "https://journals.sagepub.com/home/jpe",
    latestUrl: "https://journals.sagepub.com/home/jpe",
    folder: "城市研究期刊",
    issn: ["0739-456X", "1552-6577"],
    tags: ["城市规划", "规划教育", "规划研究"],
    description: "规划教育与规划研究期刊，覆盖城市规划理论、方法、实践和教育。",
    includeReason: "城市规划学术研究和方法来源。"
  },
  {
    id: "journal-planning-literature",
    name: "Journal of Planning Literature",
    type: "journal",
    region: "全球",
    url: "https://journals.sagepub.com/home/jpl",
    latestUrl: "https://journals.sagepub.com/home/jpl",
    folder: "城市研究期刊",
    issn: ["0885-4122", "1552-6593"],
    tags: ["城市规划", "文献综述", "理论"],
    description: "规划领域综述型期刊，用于追踪城市规划、土地利用和政策研究的知识脉络。",
    includeReason: "适合作为城市规划研究综述入口。"
  },
  {
    id: "environment-urbanization",
    name: "Environment and Urbanization",
    type: "journal",
    region: "全球南方",
    url: "https://journals.sagepub.com/home/eau",
    latestUrl: "https://journals.sagepub.com/home/eau",
    folder: "城市研究期刊",
    issn: ["0956-2478", "1746-0301"],
    tags: ["全球南方", "城市贫困", "环境"],
    description: "关注非洲、亚洲和拉美城市环境、城市贫困、住房和可持续发展的期刊。",
    includeReason: "全球南方城市与环境议题核心来源。"
  },
  {
    id: "environment-urbanization-asia",
    name: "Environment and Urbanization ASIA",
    type: "journal",
    region: "亚洲",
    url: "https://journals.sagepub.com/home/eua",
    latestUrl: "https://journals.sagepub.com/home/eua",
    folder: "城市研究期刊",
    issn: ["0975-4253", "0976-3546"],
    tags: ["亚洲城市", "城市环境", "发展"],
    description: "聚焦亚洲城市化、城市环境、基础设施和发展政策的期刊。",
    includeReason: "亚洲城市与环境研究来源。"
  },
  {
    id: "european-urban-regional-studies",
    name: "European Urban and Regional Studies",
    type: "journal",
    region: "欧洲",
    url: "https://journals.sagepub.com/home/eur",
    latestUrl: "https://journals.sagepub.com/home/eur",
    folder: "城市研究期刊",
    issn: ["0969-7764", "1461-7145"],
    tags: ["欧洲城市", "区域研究", "城市政策"],
    description: "关注欧洲城市与区域发展、城市政策、经济和社会空间变化的期刊。",
    includeReason: "欧洲城市与区域研究核心期刊。"
  },
  {
    id: "urban-climate",
    name: "Urban Climate",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/urban-climate",
    latestUrl: "https://www.sciencedirect.com/journal/urban-climate/issues",
    folder: "城市研究期刊",
    issn: ["2212-0955"],
    tags: ["城市气候", "热环境", "韧性"],
    description: "聚焦城市气候、热岛、气候适应、城市环境建模和气候韧性的期刊。",
    includeReason: "城市气候与城市韧性研究期刊。"
  },
  {
    id: "urban-ecosystems",
    name: "Urban Ecosystems",
    type: "journal",
    region: "全球",
    url: "https://link.springer.com/journal/11252",
    latestUrl: "https://link.springer.com/journal/11252/volumes-and-issues",
    folder: "城市研究期刊",
    issn: ["1083-8155", "1573-1642"],
    tags: ["城市生态", "生态系统", "生物多样性"],
    description: "研究城市生态系统、城市生物多样性、生态过程和人类活动影响的期刊。",
    includeReason: "城市生态研究核心期刊。"
  },
  {
    id: "urban-forestry-greening",
    name: "Urban Forestry & Urban Greening",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/urban-forestry-and-urban-greening",
    latestUrl: "https://www.sciencedirect.com/journal/urban-forestry-and-urban-greening/issues",
    folder: "城市研究期刊",
    issn: ["1618-8667"],
    tags: ["城市林业", "绿地", "生态服务"],
    description: "关注城市林业、城市绿化、城市绿地管理和生态系统服务的期刊。",
    includeReason: "城市绿地和自然基解决方案研究来源。"
  },
  {
    id: "journal-transport-geography",
    name: "Journal of Transport Geography",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/journal-of-transport-geography",
    latestUrl: "https://www.sciencedirect.com/journal/journal-of-transport-geography/issues",
    folder: "城市研究期刊",
    issn: ["0966-6923"],
    tags: ["交通地理", "出行", "空间结构"],
    description: "交通地理学期刊，覆盖出行、可达性、交通政策与城市空间结构。",
    includeReason: "城市交通与空间可达性研究来源。"
  },
  {
    id: "land-use-policy",
    name: "Land Use Policy",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/land-use-policy",
    latestUrl: "https://www.sciencedirect.com/journal/land-use-policy/issues",
    folder: "城市研究期刊",
    issn: ["0264-8377"],
    tags: ["土地利用", "空间政策", "规划治理"],
    description: "关注土地利用、空间政策、城市扩张和规划治理的跨学科期刊。",
    includeReason: "土地利用与城市空间政策研究来源。"
  },
  {
    id: "city-journal",
    name: "City",
    type: "journal",
    region: "全球",
    url: "https://www.tandfonline.com/journals/ccit20",
    latestUrl: "https://www.tandfonline.com/toc/ccit20/current",
    folder: "城市研究期刊",
    issn: ["1360-4813", "1470-3629"],
    tags: ["城市理论", "城市变化", "批判城市研究"],
    description: "City: analysis of urban change, theory, action，关注城市变化、理论和行动导向研究。",
    includeReason: "批判城市研究和城市理论来源。"
  },
  {
    id: "journal-urban-history",
    name: "Journal of Urban History",
    type: "journal",
    region: "全球",
    url: "https://journals.sagepub.com/home/juh",
    latestUrl: "https://journals.sagepub.com/home/juh",
    folder: "城市研究期刊",
    issn: ["0096-1442", "1552-6771"],
    tags: ["城市史", "历史城市", "社会史"],
    description: "城市史国际期刊，关注城市历史、城市社会和历史空间过程。",
    includeReason: "城市历史研究来源。"
  },
  {
    id: "housing-studies",
    name: "Housing Studies",
    type: "journal",
    region: "全球",
    url: "https://www.tandfonline.com/journals/chos20",
    latestUrl: "https://www.tandfonline.com/toc/chos20/current",
    folder: "城市研究期刊",
    issn: ["0267-3037", "1466-1810"],
    tags: ["住房", "社区", "城市政策"],
    description: "住房研究期刊，覆盖住房政策、住房市场、居住公平和城市社会问题。",
    includeReason: "城市住房与居住政策研究期刊。"
  },
  {
    id: "urban-planning-cogitatio",
    name: "Urban Planning",
    type: "journal",
    region: "全球",
    url: "https://www.cogitatiopress.com/urbanplanning",
    latestUrl: "https://www.cogitatiopress.com/urbanplanning/issue/current",
    folder: "城市研究期刊",
    issn: ["2183-7635"],
    tags: ["开放获取", "城市规划", "城市治理"],
    description: "开放获取城市规划期刊，关注城市治理、规划理论、空间转型和可持续城市。",
    includeReason: "开放获取城市规划研究来源。"
  },
  {
    id: "journal-urban-management",
    name: "Journal of Urban Management",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/journal-of-urban-management",
    latestUrl: "https://www.sciencedirect.com/journal/journal-of-urban-management/issues",
    folder: "城市研究期刊",
    issn: ["2226-5856"],
    tags: ["城市管理", "规划治理", "城市政策"],
    description: "聚焦城市管理、规划治理、城市政策和城市发展实践的期刊。",
    includeReason: "城市管理与规划治理研究来源。"
  },
  {
    id: "articulo",
    name: "Articulo - Journal of Urban Research",
    type: "journal",
    region: "欧洲/全球",
    url: "https://journals.openedition.org/articulo/",
    latestUrl: "https://journals.openedition.org/articulo/",
    folder: "城市研究期刊",
    issn: ["1661-4941"],
    tags: ["开放获取", "城市议题", "多语种"],
    description: "开放获取城市研究期刊，发表城市问题相关理论、实证研究和专题论文。",
    includeReason: "开放获取、多语种城市研究来源。"
  }
];

// 城市多源大数据：提供城市相关数据的开放平台、数据供应商、遥感与地图数据源。
// 来源：收藏夹「城市多源大数据 / 政府官方数据库 / 城市大数据供应商 / 宏观地理数据 / 开放地图API / 交通数据分析 / 舆情指数分析」筛选 + 收藏夹外补充检索。
// category: gov 政府开放 | geo 地理遥感 | mobility 时空人口 | api 地图API | thematic 专题数据
const URBAN_DATA_SOURCES = [
  {
    id: "shenzhen-opendata",
    name: "深圳市政府数据开放平台",
    category: "gov",
    origin: "中国",
    url: "https://opendata.sz.gov.cn/",
    tags: ["开放数据", "政府数据", "中国城市"],
    description: "深圳市统一政府数据开放门户，提供交通、人口、城市运行等多领域可下载数据集与API。",
    descriptionEn: "Shenzhen's official open-government data portal with downloadable datasets and APIs across transport, population, and city operations."
  },
  {
    id: "us-census",
    name: "U.S. Census Bureau",
    category: "gov",
    origin: "美国",
    url: "https://www.census.gov/",
    tags: ["人口数据", "政府数据", "开放数据"],
    description: "美国人口普查局，提供人口、住房、经济等权威普查与社区调查数据（含API）。",
    descriptionEn: "The U.S. Census Bureau, offering authoritative population, housing, and economic census and survey data with APIs."
  },
  {
    id: "worldbank-data",
    name: "World Bank Open Data",
    category: "gov",
    origin: "全球",
    url: "https://data.worldbank.org/",
    tags: ["开放数据", "社会经济", "全球指标"],
    description: "世界银行开放数据，覆盖各国发展、人口、城市化、经济等长期指标，可视化与下载。",
    descriptionEn: "World Bank Open Data with long-run development, population, urbanization, and economic indicators for countries worldwide."
  },
  {
    id: "oecd-data",
    name: "OECD Data Explorer",
    category: "gov",
    origin: "全球",
    url: "https://data-explorer.oecd.org/",
    tags: ["经济数据", "统计数据", "开放数据"],
    description: "经合组织数据浏览器，提供区域、城市、经济与社会主题的标准化统计数据。",
    descriptionEn: "OECD's data explorer with standardized statistics on regions, cities, and economic and social themes."
  },
  {
    id: "humdata-hdx",
    name: "Humanitarian Data Exchange (HDX)",
    category: "gov",
    origin: "全球",
    url: "https://data.humdata.org/",
    tags: ["开放数据", "人道数据", "地理空间"],
    description: "联合国 OCHA 运营的人道数据平台，汇集人口、边界、灾害、基础设施等地理空间数据。",
    descriptionEn: "UN OCHA's humanitarian data platform aggregating population, boundary, disaster, and infrastructure geospatial datasets."
  },
  {
    id: "china-stats",
    name: "国家统计局",
    category: "gov",
    origin: "中国",
    url: "https://www.stats.gov.cn/",
    tags: ["统计数据", "人口数据", "开放数据"],
    description: "中国国家统计局，提供全国与分省市的人口、经济、社会统计年鉴与年度数据查询。",
    descriptionEn: "China's National Bureau of Statistics, providing national and provincial population, economic, and social statistical yearbooks."
  },
  {
    id: "usgs-earthexplorer",
    name: "USGS EarthExplorer",
    category: "geo",
    origin: "全球",
    url: "https://earthexplorer.usgs.gov/",
    tags: ["遥感", "卫星影像", "高程数据"],
    description: "美国地质调查局影像检索平台，免费下载 Landsat、航拍、DEM 等遥感与高程数据。",
    descriptionEn: "USGS imagery portal for free download of Landsat, aerial, and DEM remote-sensing and elevation data."
  },
  {
    id: "google-earth-engine",
    name: "Google Earth Engine",
    category: "geo",
    origin: "全球",
    url: "https://earthengine.google.com/",
    tags: ["遥感", "地理空间", "云计算"],
    description: "谷歌地球引擎，PB 级卫星影像与地理数据集的云端分析平台，适合大尺度城市遥感分析。",
    descriptionEn: "Google's cloud platform for petabyte-scale satellite imagery and geospatial analysis, suited to large-scale urban remote sensing."
  },
  {
    id: "nasa-earthdata",
    name: "NASA Earthdata",
    category: "geo",
    origin: "全球",
    url: "https://www.earthdata.nasa.gov/",
    tags: ["遥感", "对地观测", "开放数据"],
    description: "NASA 对地观测数据门户，覆盖大气、土地、海洋、人居等开放地球科学数据集。",
    descriptionEn: "NASA's earth-observation data portal spanning atmosphere, land, ocean, and human-settlement open datasets."
  },
  {
    id: "copernicus-dataspace",
    name: "Copernicus Data Space (Sentinel)",
    category: "geo",
    origin: "欧洲",
    url: "https://dataspace.copernicus.eu/",
    tags: ["遥感", "卫星影像", "对地观测"],
    description: "欧盟哥白尼计划数据空间，免费提供 Sentinel 系列卫星影像与对地观测产品。",
    descriptionEn: "The EU Copernicus data space offering free Sentinel satellite imagery and earth-observation products."
  },
  {
    id: "openstreetmap-data",
    name: "OpenStreetMap",
    category: "geo",
    origin: "全球",
    url: "https://www.openstreetmap.org/",
    tags: ["开放地图", "地理空间", "开放数据"],
    description: "全球协作开放地图，含道路、建筑、用地与POI矢量数据，可经Overpass/Geofabrik批量下载。",
    descriptionEn: "Global collaborative open map with roads, buildings, land use, and POI vectors, downloadable via Overpass/Geofabrik."
  },
  {
    id: "overture-maps",
    name: "Overture Maps Foundation",
    category: "geo",
    origin: "全球",
    url: "https://overturemaps.org/",
    tags: ["开放地图", "POI", "建筑轮廓"],
    description: "由多家科技公司共建的开放地图数据，提供标准化的地点(POI)、建筑、交通与行政要素。",
    descriptionEn: "Open map data backed by major tech firms, providing standardized places (POI), buildings, transportation, and admin layers."
  },
  {
    id: "gadm",
    name: "GADM 全球行政边界",
    category: "geo",
    origin: "全球",
    url: "https://gadm.org/",
    tags: ["行政边界", "地理空间", "开放数据"],
    description: "全球各级行政区划边界矢量数据库，常用于制图与空间统计的底层边界。",
    descriptionEn: "A global database of administrative boundary vectors at all levels, widely used as a base layer for mapping and spatial stats."
  },
  {
    id: "worldpop",
    name: "WorldPop",
    category: "geo",
    origin: "全球",
    url: "https://www.worldpop.org/",
    tags: ["人口数据", "栅格数据", "开放数据"],
    description: "高分辨率人口分布栅格数据，提供各国逐网格人口、年龄结构与流动估算。",
    descriptionEn: "High-resolution gridded population data with per-cell counts, age structure, and mobility estimates by country."
  },
  {
    id: "gscloud",
    name: "地理空间数据云",
    category: "geo",
    origin: "中国",
    url: "http://www.gscloud.cn/",
    tags: ["遥感", "高程数据", "卫星影像"],
    description: "中科院地理空间数据云，提供 Landsat、MODIS、DEM 等遥感数据的中文检索下载。",
    descriptionEn: "CAS Geospatial Data Cloud offering Chinese-language search and download of Landsat, MODIS, and DEM data."
  },
  {
    id: "quanturban",
    name: "量城科技 QuantUrban",
    category: "mobility",
    origin: "中国",
    url: "https://quanturban.com/",
    tags: ["城市大数据", "时空数据", "决策咨询"],
    description: "城市时空大数据产品与决策咨询，提供人口活动、职住、城市体检等数据服务。",
    descriptionEn: "Urban spatiotemporal big-data products and consulting, covering population activity, jobs-housing, and city diagnostics."
  },
  {
    id: "smartsteps",
    name: "智慧足迹 Smartsteps",
    category: "mobility",
    origin: "中国",
    url: "https://www.smartsteps.com/",
    tags: ["位置大数据", "时空数据", "人口热力"],
    description: "基于运营商信令的位置大数据服务商，提供人口热力、流动与职住分析。",
    descriptionEn: "A location big-data provider based on carrier signaling, offering population heat, flow, and jobs-housing analytics."
  },
  {
    id: "talkingdata",
    name: "TalkingData",
    category: "mobility",
    origin: "中国",
    url: "https://www.talkingdata.com/",
    tags: ["移动数据", "位置大数据", "数据智能"],
    description: "移动互联网数据服务商，提供人群画像、位置洞察与城市消费等数据智能产品。",
    descriptionEn: "A mobile-data company providing audience profiling, location insight, and urban consumption data-intelligence products."
  },
  {
    id: "geohey",
    name: "极海 GeoHey",
    category: "mobility",
    origin: "中国",
    url: "https://geohey.com/",
    tags: ["地理大数据", "空间分析", "数据可视化"],
    description: "地理大数据平台，整合人口、商业、地块等多源数据并提供空间分析与可视化。",
    descriptionEn: "A geospatial big-data platform integrating population, commercial, and parcel data with spatial analysis and visualization."
  },
  {
    id: "udparty",
    name: "城市数据派",
    category: "mobility",
    origin: "中国",
    url: "https://www.udparty.com/",
    tags: ["城市数据", "数据社区", "开放数据"],
    description: "城市数据从业者社区，汇总开放数据源、案例与教程，是数据获取的重要入口。",
    descriptionEn: "A community for urban-data practitioners aggregating open data sources, cases, and tutorials."
  },
  {
    id: "amap-lbs",
    name: "高德开放平台",
    category: "api",
    origin: "中国",
    url: "https://lbs.amap.com/",
    tags: ["地图API", "POI", "出行"],
    description: "高德地图开放平台，提供POI搜索、路径规划、逆地理编码与交通态势等API。",
    descriptionEn: "Amap's open platform with APIs for POI search, routing, reverse geocoding, and traffic conditions."
  },
  {
    id: "baidu-lbs",
    name: "百度地图开放平台",
    category: "api",
    origin: "中国",
    url: "https://lbsyun.baidu.com/",
    tags: ["地图API", "POI", "路径规划"],
    description: "百度地图开放平台，提供地图、检索、定位、路线与全景等Web与SDK接口。",
    descriptionEn: "Baidu Maps open platform with web and SDK APIs for maps, search, positioning, routing, and panorama."
  },
  {
    id: "baidu-huiyan",
    name: "百度地图慧眼",
    category: "api",
    origin: "中国",
    url: "https://huiyan.baidu.com/",
    tags: ["位置大数据", "人口迁徙", "时空数据"],
    description: "百度位置大数据平台，提供人口画像、迁徙、客流与商圈分析等城市洞察。",
    descriptionEn: "Baidu's location big-data platform offering population profiles, migration, footfall, and trade-area urban insights."
  },
  {
    id: "cma-data",
    name: "中国气象数据网",
    category: "thematic",
    origin: "中国",
    url: "http://data.cma.cn/",
    tags: ["气象数据", "气候", "开放数据"],
    description: "国家气象信息中心数据门户，提供地面、辐射、气候等观测与再分析气象数据。",
    descriptionEn: "China Meteorological Data Service Center with surface, radiation, and climate observation and reanalysis data."
  },
  {
    id: "baidu-jiaotong",
    name: "百度地图交通大数据",
    category: "thematic",
    origin: "中国",
    url: "https://jiaotong.baidu.com/",
    tags: ["交通数据", "拥堵指数", "出行"],
    description: "百度交通大数据平台，发布城市实时与历史拥堵指数、出行与通勤分析报告。",
    descriptionEn: "Baidu's traffic big-data platform publishing real-time/historical congestion indices and commuting analytics."
  },
  {
    id: "baidu-index",
    name: "百度指数",
    category: "thematic",
    origin: "中国",
    url: "https://index.baidu.com/",
    tags: ["搜索指数", "舆情", "趋势分析"],
    description: "基于搜索行为的趋势与需求图谱工具，可用于城市议题热度与舆情的代理观测。",
    descriptionEn: "A search-trend and demand-graph tool usable as a proxy for the popularity of urban topics and public attention."
  },
  {
    id: "metrodb",
    name: "深圳地铁数据库 MetroDB",
    category: "thematic",
    origin: "中国",
    url: "https://metrodb.org/",
    tags: ["交通数据", "地铁客流", "城市数据"],
    description: "整理城市轨道交通线路、站点与客流的数据库，便于查询地铁运营与客流量。",
    descriptionEn: "A database of metro lines, stations, and ridership for querying rail-transit operations and passenger flows."
  }
];

// 数据可视化工具：图表/BI、地理可视化、编程库、词云文本与统计分析工具。
// 来源：收藏夹「数据可视化软件 / AI数据分析产品 / 城市分析平台」筛选 + 收藏夹外补充检索。
// category: chart 图表与BI | geo 地理可视化 | code 编程库 | text 词云文本 | stat 统计分析
const DATAVIZ_TOOLS = [
  {
    id: "echarts",
    name: "Apache ECharts",
    category: "code",
    origin: "全球",
    url: "https://echarts.apache.org/",
    tags: ["开源", "图表库", "数据可视化"],
    description: "Apache 开源 JavaScript 图表库，支持折线、地图、关系图等丰富类型，中文社区活跃。",
    descriptionEn: "An Apache open-source JavaScript charting library with rich chart types including maps and graphs."
  },
  {
    id: "d3js",
    name: "D3.js",
    category: "code",
    origin: "全球",
    url: "https://d3js.org/",
    tags: ["开源", "可视化库", "SVG"],
    description: "底层数据驱动可视化库，基于 SVG/Canvas 自由定制几乎任意图形，业界标杆。",
    descriptionEn: "A low-level, data-driven visualization library for building almost any custom graphic on SVG/Canvas."
  },
  {
    id: "observable-plot",
    name: "Observable Plot",
    category: "code",
    origin: "全球",
    url: "https://observablehq.com/plot/",
    tags: ["开源", "图形语法", "快速绘图"],
    description: "D3 团队推出的高层图形语法库，用少量代码快速生成探索性图表。",
    descriptionEn: "A high-level grammar-of-graphics library from the D3 team for quick exploratory charts with minimal code."
  },
  {
    id: "plotly",
    name: "Plotly",
    category: "code",
    origin: "美国",
    url: "https://plotly.com/",
    tags: ["可视化库", "交互图表", "多语言"],
    description: "支持 Python/R/JS 的交互式可视化库，含 40+ 图表类型与 Dash 仪表盘框架。",
    descriptionEn: "An interactive visualization library for Python/R/JS with 40+ chart types and the Dash dashboard framework."
  },
  {
    id: "vega-lite",
    name: "Vega-Lite",
    category: "code",
    origin: "全球",
    url: "https://vega.github.io/vega-lite/",
    tags: ["开源", "图形语法", "声明式"],
    description: "声明式可视化语法，用 JSON 规格描述统计图形，适合快速、可复用的图表生成。",
    descriptionEn: "A declarative visualization grammar describing statistical graphics as JSON specs for fast, reusable charts."
  },
  {
    id: "tableau",
    name: "Tableau",
    category: "chart",
    origin: "美国",
    url: "https://www.tableau.com/",
    tags: ["商业智能", "仪表盘", "数据可视化"],
    description: "主流商业智能与可视化平台，拖拽式构建交互仪表盘，支持地理与多源数据。",
    descriptionEn: "A leading BI and visualization platform for building interactive dashboards with drag-and-drop and geo support."
  },
  {
    id: "powerbi",
    name: "Microsoft Power BI",
    category: "chart",
    origin: "美国",
    url: "https://powerbi.microsoft.com/",
    tags: ["商业智能", "仪表盘", "数据分析"],
    description: "微软商业智能工具，连接多源数据生成报表与仪表盘，集成 Office 生态。",
    descriptionEn: "Microsoft's BI tool for connecting multi-source data to build reports and dashboards within the Office ecosystem."
  },
  {
    id: "datawrapper",
    name: "Datawrapper",
    category: "chart",
    origin: "欧洲",
    url: "https://www.datawrapper.de/",
    tags: ["在线图表", "数据新闻", "地图"],
    description: "面向新闻与报告的在线制图工具，几步生成可发布的图表、地图与表格。",
    descriptionEn: "An online charting tool for newsrooms and reports, producing publishable charts, maps, and tables in a few steps."
  },
  {
    id: "rawgraphs",
    name: "RAWGraphs",
    category: "chart",
    origin: "全球",
    url: "https://www.rawgraphs.io/",
    tags: ["开源", "在线图表", "探索性可视化"],
    description: "开源在线工具，擅长把表格数据快速映射为非常规、探索性的可视化图形。",
    descriptionEn: "An open-source online tool specialized in mapping tabular data into unconventional, exploratory visualizations."
  },
  {
    id: "flourish",
    name: "Flourish",
    category: "chart",
    origin: "英国",
    url: "https://flourish.studio/",
    tags: ["在线图表", "动态可视化", "数据新闻"],
    description: "模板化在线可视化工具，无需编程即可制作动态、可叙事的图表与滚动故事。",
    descriptionEn: "A template-based online tool for making animated, narrative charts and scrollytelling stories without coding."
  },
  {
    id: "chartcube",
    name: "ChartCube（AntV）",
    category: "chart",
    origin: "中国",
    url: "https://chartcube.alipay.com/",
    tags: ["在线图表", "AntV", "数据可视化"],
    description: "蚂蚁 AntV 出品的在线图表制作工具，上传数据即可生成规范、美观的图表。",
    descriptionEn: "An online chart maker by Ant Group's AntV, generating clean, well-styled charts from uploaded data."
  },
  {
    id: "highcharts",
    name: "Highcharts",
    category: "code",
    origin: "全球",
    url: "https://www.highcharts.com/",
    tags: ["图表库", "交互图表", "可视化库"],
    description: "成熟的商用 JavaScript 图表库，API 完善、兼容性好，广泛用于Web交互图表。",
    descriptionEn: "A mature commercial JavaScript charting library with a complete API and broad compatibility for web charts."
  },
  {
    id: "keplergl",
    name: "kepler.gl",
    category: "geo",
    origin: "全球",
    url: "https://kepler.gl/",
    tags: ["地理可视化", "大数据地图", "WebGL"],
    description: "Uber 开源的地理大数据可视化工具，拖拽即可对百万级点线进行地图渲染与时序动画。",
    descriptionEn: "Uber's open-source geospatial tool for drag-and-drop mapping and time animation of millions of points and lines."
  },
  {
    id: "deckgl",
    name: "deck.gl",
    category: "geo",
    origin: "全球",
    url: "https://deck.gl/",
    tags: ["地理可视化", "WebGL", "大规模数据"],
    description: "基于 WebGL 的大规模地理可视化框架，支持图层化渲染海量空间数据，kepler.gl 的底层引擎。",
    descriptionEn: "A WebGL framework for large-scale geospatial visualization with layered rendering; the engine behind kepler.gl."
  },
  {
    id: "leaflet",
    name: "Leaflet",
    category: "geo",
    origin: "全球",
    url: "https://leafletjs.com/",
    tags: ["交互地图", "地图库", "开源"],
    description: "轻量开源交互地图库，体积小、插件丰富，是 Web 嵌入地图的常用方案。",
    descriptionEn: "A lightweight open-source interactive-map library with a small footprint and rich plugins for embedding web maps."
  },
  {
    id: "flowmap-blue",
    name: "Flowmap.blue",
    category: "geo",
    origin: "全球",
    url: "https://www.flowmap.blue/",
    tags: ["流向图", "地理可视化", "OD可视化"],
    description: "在线流向图工具，从起讫(OD)表格直接生成空间流动可视化，适合通勤与迁徙。",
    descriptionEn: "An online flow-map tool that turns origin-destination tables into spatial flow visualizations for commuting and migration."
  },
  {
    id: "sanddance",
    name: "SandDance",
    category: "geo",
    origin: "全球",
    url: "https://microsoft.github.io/SandDance/",
    tags: ["三维可视化", "数据探索", "交互"],
    description: "微软开源的数据探索可视化，用统一的单位可视化在 2D/3D 间流畅过渡探索数据。",
    descriptionEn: "Microsoft's open-source unit-visualization tool for fluidly exploring data across 2D/3D views."
  },
  {
    id: "maptable",
    name: "MapTable",
    category: "geo",
    origin: "中国",
    url: "https://maptable.com/",
    tags: ["空间可视化", "在线制图", "数据地图"],
    description: "在线空间数据分析与制图平台，支持上传数据、空间分析并发布交互数据地图。",
    descriptionEn: "An online platform for spatial analysis and mapping, supporting data upload, analysis, and publishing interactive maps."
  },
  {
    id: "gephi",
    name: "Gephi",
    category: "code",
    origin: "全球",
    url: "https://gephi.org/",
    tags: ["网络分析", "图可视化", "开源"],
    description: "开源网络与图可视化软件，适合社会网络、交通网络等关系数据的布局与分析。",
    descriptionEn: "Open-source network and graph visualization software for laying out and analyzing relational data like social or transport networks."
  },
  {
    id: "qgis",
    name: "QGIS",
    category: "geo",
    origin: "全球",
    url: "https://qgis.org/",
    tags: ["GIS", "地图制图", "开源"],
    description: "免费开源的桌面 GIS，集空间数据处理、分析与高质量地图制图于一体。",
    descriptionEn: "A free, open-source desktop GIS combining spatial data processing, analysis, and high-quality cartography."
  },
  {
    id: "weiciyun",
    name: "微词云",
    category: "text",
    origin: "中国",
    url: "https://www.weiciyun.com/",
    tags: ["词云", "文本可视化", "在线工具"],
    description: "在线词云与文本可视化工具，支持分词、形状与配色自定义，适合舆情与文本呈现。",
    descriptionEn: "An online word-cloud and text-visualization tool with segmentation, shapes, and color customization."
  },
  {
    id: "wordart",
    name: "WordArt",
    category: "text",
    origin: "全球",
    url: "https://wordart.com/",
    tags: ["词云", "文本可视化", "在线工具"],
    description: "在线词云生成器，支持自定义形状、字体与导出，适合快速制作艺术化词云。",
    descriptionEn: "An online word-cloud generator with custom shapes, fonts, and export for quick artistic word clouds."
  },
  {
    id: "picdata",
    name: "图悦",
    category: "text",
    origin: "中国",
    url: "http://www.picdata.cn/",
    tags: ["词云", "词频分析", "文本可视化"],
    description: "中文在线词频分析与词云制作工具，可批量统计高频词并生成词云图。",
    descriptionEn: "A Chinese online word-frequency and word-cloud tool that tallies high-frequency terms and renders clouds."
  },
  {
    id: "spsspro",
    name: "SPSSPRO",
    category: "stat",
    origin: "中国",
    url: "https://www.spsspro.com/",
    tags: ["统计分析", "在线SPSS", "数据分析"],
    description: "免费在线统计分析平台，覆盖描述、回归、因子等方法并自动给出图表与解读。",
    descriptionEn: "A free online statistical-analysis platform covering descriptive, regression, and factor methods with auto charts and interpretation."
  },
  {
    id: "spssau",
    name: "SPSSAU",
    category: "stat",
    origin: "中国",
    url: "https://spssau.com/",
    tags: ["统计分析", "在线SPSS", "问卷分析"],
    description: "在线 SPSS 分析工具，面向问卷与科研数据提供相关、回归、信效度等一站式分析。",
    descriptionEn: "An online SPSS-style tool offering correlation, regression, and reliability/validity analysis for surveys and research data."
  },
  {
    id: "tuzhidian",
    name: "图之典",
    category: "chart",
    origin: "中国",
    url: "http://tuzhidian.com/",
    tags: ["图表词典", "数据可视化", "设计参考"],
    description: "中文图表类型词典，系统梳理各类图表的定义、适用场景与示例，便于选型。",
    descriptionEn: "A Chinese dictionary of chart types cataloging definitions, use cases, and examples to aid chart selection."
  },
  {
    id: "mapbox-isochrone",
    name: "Mapbox Isochrone Playground",
    category: "analysis",
    origin: "全球",
    url: "https://docs.mapbox.com/playground/isochrone/",
    tags: ["等时圈", "可达性", "15分钟城市"],
    description: "Mapbox 官方等时圈演练场，输入位置与时间即可生成步行/骑行/驾车可达范围，是做 15 分钟城市与可达性分析的直接入口。",
    descriptionEn: "Mapbox's official isochrone playground generates walk/bike/drive reachability from a point and time budget — a direct entry to 15-minute-city and accessibility analysis."
  },
  {
    id: "smappen",
    name: "smappen",
    category: "analysis",
    origin: "全球",
    url: "https://www.smappen.com/",
    tags: ["等时圈", "可达性", "场地分析"],
    description: "在线等时圈与商圈分析工具，快速绘制出行时间范围并叠加人口、POI 等数据，常用于选址与 15 分钟生活圈分析。",
    descriptionEn: "An online isochrone and catchment tool that draws travel-time areas and overlays population and POI data for site selection and 15-minute-city analysis."
  },
  {
    id: "traveltime",
    name: "TravelTime",
    category: "analysis",
    origin: "全球",
    url: "https://traveltime.com/",
    tags: ["等时圈", "可达性", "出行"],
    description: "以出行时间为核心的可达性分析平台与 API，支持多模式等时圈、通勤与选址分析。",
    descriptionEn: "A travel-time-centric accessibility platform and API supporting multimodal isochrones, commuting, and location analysis."
  },
  {
    id: "carto-analysis",
    name: "CARTO",
    category: "analysis",
    origin: "全球",
    url: "https://carto.com/",
    tags: ["地理空间分析", "云平台", "可视化"],
    description: "云原生地理空间分析平台，支持空间 SQL、区位分析与大规模地理数据的建模与可视化。",
    descriptionEn: "A cloud-native geospatial analysis platform with spatial SQL, location analysis, and large-scale geodata modeling and visualization."
  },
  {
    id: "urbanfootprint",
    name: "UrbanFootprint",
    category: "analysis",
    origin: "美国",
    url: "https://urbanfootprint.com/",
    tags: ["规划分析", "情景模拟", "土地利用"],
    description: "面向规划的城市分析平台，整合土地利用、交通与环境数据，支持情景构建与影响评估。",
    descriptionEn: "A planning-oriented urban analytics platform integrating land use, transport, and environmental data for scenario building and impact assessment."
  },
  {
    id: "conveyal",
    name: "Conveyal",
    category: "analysis",
    origin: "美国",
    url: "https://conveyal.com/",
    tags: ["公交可达", "情景模拟", "交通"],
    description: "公共交通可达性分析工具，基于 GTFS 与路网评估不同交通方案下的出行可达性，支持情景对比。",
    descriptionEn: "A transit accessibility tool using GTFS and street networks to evaluate reachability under different transport scenarios."
  },
  {
    id: "arcgis-urban",
    name: "ArcGIS Urban",
    category: "analysis",
    origin: "全球",
    url: "https://www.esri.com/en-us/arcgis/products/arcgis-urban/overview",
    tags: ["三维规划", "城市设计", "情景模拟"],
    description: "Esri 的三维城市规划与设计平台，支持地块开发、分区与城市设计方案的情景模拟与评估。",
    descriptionEn: "Esri's 3D city planning and design platform for parcel development, zoning, and scenario simulation of urban design proposals."
  },
  {
    id: "social-explorer-tool",
    name: "Social Explorer",
    category: "analysis",
    origin: "美国",
    url: "https://www.socialexplorer.com/",
    tags: ["社会分析", "人口数据", "地图"],
    description: "人口与社会经济数据的交互分析与制图平台，可快速生成人口统计地图与专题分析。",
    descriptionEn: "An interactive platform for demographic and socioeconomic data, producing population maps and thematic analysis quickly."
  },
  {
    id: "digital-blue-foam",
    name: "Digital Blue Foam",
    category: "analysis",
    origin: "全球",
    url: "https://www.digitalbluefoam.com/",
    tags: ["生成式设计", "AI分析", "场地分析"],
    description: "AI 驱动的生成式城市设计与场地分析工具，快速生成并评估城市与建筑方案的多种可能。",
    descriptionEn: "An AI-driven generative urban design and site-analysis tool that rapidly generates and evaluates city and building options."
  },
  {
    id: "uatp",
    name: "Urban Analytics Technology Platform",
    category: "analysis",
    origin: "全球",
    url: "https://urban-analytics-technology-platform.github.io/",
    tags: ["开源", "城市分析", "空间分析"],
    description: "开源城市分析技术平台，汇集可复用的城市数据分析与建模工具，面向研究与规划实践。",
    descriptionEn: "An open-source urban analytics technology platform gathering reusable tools for urban data analysis and modeling."
  },
  {
    id: "replica",
    name: "Replica",
    category: "analysis",
    origin: "美国",
    url: "https://www.replicahq.com/",
    tags: ["活动数据", "出行", "城市模拟"],
    description: "以合成活动数据重建城市出行与人口活动的平台，为交通与土地利用决策提供分析支持。",
    descriptionEn: "A platform reconstructing urban travel and population activity with synthetic activity data to support transport and land-use decisions."
  }
];

// 学术文献与检索：文献横断检索入口——综合搜索、引文索引、开放获取、中文库与文献探索工具。
// access: "subscription" 的条目多需机构订阅/登录，卡片会显示「需订阅」标记。
// category: general 综合检索 | index 引文索引 | oa 开放获取 | cn 中文文献 | tool 探索工具
const ACADEMIC_SOURCES = [
  {
    id: "google-scholar",
    name: "Google Scholar",
    category: "general",
    origin: "全球",
    access: "open",
    url: "https://scholar.google.com/",
    tags: ["学术搜索", "免费", "引文追踪"],
    description: "覆盖各学科的免费学术搜索引擎，常附全文PDF链接与被引统计，城市研究检索的首选入口。",
    descriptionEn: "A free cross-discipline scholarly search engine with full-text links and citation counts; a first stop for urban-research search."
  },
  {
    id: "semantic-scholar",
    name: "Semantic Scholar",
    category: "general",
    origin: "美国",
    access: "open",
    url: "https://www.semanticscholar.org/",
    tags: ["学术搜索", "AI检索", "论文图谱"],
    description: "Allen AI 的免费学术检索，用 NLP 生成论文摘要、引用脉络与相关文献图谱。",
    descriptionEn: "Allen AI's free scholarly search using NLP to surface summaries, citation context, and related-paper graphs."
  },
  {
    id: "openalex",
    name: "OpenAlex",
    category: "general",
    origin: "全球",
    access: "open",
    url: "https://openalex.org/",
    tags: ["开放数据", "学术图谱", "免费"],
    description: "开放的学术元数据库，收录 2.5 亿+作品、作者与机构，含免费API，适合文献计量分析。",
    descriptionEn: "An open scholarly metadata database of 250M+ works, authors, and institutions with a free API for bibliometrics."
  },
  {
    id: "base-search",
    name: "BASE",
    category: "general",
    origin: "欧洲",
    access: "open",
    url: "https://www.base-search.net/",
    tags: ["开放获取", "学术搜索", "元数据"],
    description: "德国比勒费尔德大学的开放获取学术搜索引擎，聚合全球仓储的数亿条文献元数据。",
    descriptionEn: "Bielefeld University's open-access academic search engine aggregating hundreds of millions of records from repositories."
  },
  {
    id: "core-ac",
    name: "CORE",
    category: "general",
    origin: "英国",
    access: "open",
    url: "https://core.ac.uk/",
    tags: ["开放获取", "全文聚合", "免费"],
    description: "全球最大的开放获取论文全文聚合平台，提供检索、API 与数据集下载。",
    descriptionEn: "The world's largest aggregator of open-access full texts, offering search, an API, and dataset downloads."
  },
  {
    id: "web-of-science",
    name: "Web of Science",
    category: "index",
    origin: "全球",
    access: "subscription",
    url: "https://www.webofscience.com/",
    tags: ["引文索引", "核心合集", "文献计量"],
    description: "权威引文索引数据库，核心合集适合系统综述、引文追踪与期刊层面分析（多需机构订阅）。",
    descriptionEn: "An authoritative citation index; its Core Collection suits systematic reviews and citation tracking (subscription)."
  },
  {
    id: "scopus",
    name: "Scopus",
    category: "index",
    origin: "全球",
    access: "subscription",
    url: "https://www.scopus.com/",
    tags: ["引文索引", "摘要库", "文献计量"],
    description: "爱思唯尔的大型同行评审文献摘要与引文库，覆盖科学、社科与人文（多需机构订阅）。",
    descriptionEn: "Elsevier's large abstract and citation database of peer-reviewed literature across sciences, social sciences, and humanities (subscription)."
  },
  {
    id: "dimensions",
    name: "Dimensions",
    category: "index",
    origin: "全球",
    access: "open",
    url: "https://www.dimensions.ai/",
    tags: ["引文索引", "科研情报", "免费"],
    description: "关联论文、专利、基金与临床试验的科研情报平台，提供免费版检索。",
    descriptionEn: "A research-intelligence platform linking papers, patents, grants, and trials, with a free search tier."
  },
  {
    id: "lens-org",
    name: "The Lens",
    category: "index",
    origin: "全球",
    access: "open",
    url: "https://www.lens.org/",
    tags: ["文献专利", "开放获取", "检索"],
    description: "免费整合学术文献与全球专利的检索分析平台，适合创新与技术演进研究。",
    descriptionEn: "A free platform integrating scholarly works and global patents for innovation and technology-trend analysis."
  },
  {
    id: "arxiv",
    name: "arXiv",
    category: "oa",
    origin: "全球",
    access: "open",
    url: "https://arxiv.org/",
    tags: ["预印本", "开放获取", "免费"],
    description: "康奈尔大学的开放预印本库，城市计算、空间分析等方向可获取最新未刊研究。",
    descriptionEn: "Cornell's open preprint server; a source of the latest unpublished work in urban computing and spatial analysis."
  },
  {
    id: "doaj",
    name: "DOAJ",
    category: "oa",
    origin: "全球",
    access: "open",
    url: "https://doaj.org/",
    tags: ["开放获取", "期刊目录", "免费"],
    description: "开放获取期刊目录，收录经审核的高质量 OA 期刊与文章，可按学科检索。",
    descriptionEn: "The Directory of Open Access Journals, indexing vetted high-quality OA journals and articles searchable by discipline."
  },
  {
    id: "ssrn",
    name: "SSRN",
    category: "oa",
    origin: "全球",
    access: "open",
    url: "https://www.ssrn.com/",
    tags: ["预印本", "社会科学", "开放获取"],
    description: "社会科学预印本与工作论文库，城市经济、规划与政策研究的早期成果常在此发布。",
    descriptionEn: "A social-sciences preprint and working-paper repository where early urban economics, planning, and policy work often appears."
  },
  {
    id: "ia-scholar",
    name: "Internet Archive Scholar",
    category: "oa",
    origin: "全球",
    access: "open",
    url: "https://scholar.archive.org/",
    tags: ["开放获取", "全文存档", "免费"],
    description: "互联网档案馆的学术全文检索，专注长期保存的开放获取论文与灰色文献。",
    descriptionEn: "The Internet Archive's scholarly full-text search focused on preserved open-access papers and grey literature."
  },
  {
    id: "cnki",
    name: "中国知网 CNKI",
    category: "cn",
    origin: "中国",
    access: "subscription",
    url: "https://www.cnki.net/",
    tags: ["中文库", "期刊论文", "学位论文"],
    description: "中国最大的学术文献库，覆盖期刊、学位论文、会议与年鉴，中文城市研究首选（多需订阅）。",
    descriptionEn: "China's largest academic database spanning journals, theses, conferences, and yearbooks; the primary Chinese-language source (subscription)."
  },
  {
    id: "wanfang",
    name: "万方数据",
    category: "cn",
    origin: "中国",
    access: "subscription",
    url: "https://www.wanfangdata.com.cn/",
    tags: ["中文库", "期刊论文", "学位论文"],
    description: "综合性中文文献库，含期刊、学位论文、会议与标准，常与知网互补（多需订阅）。",
    descriptionEn: "A comprehensive Chinese-language database of journals, theses, conferences, and standards, complementary to CNKI (subscription)."
  },
  {
    id: "ncpssd",
    name: "国家哲学社会科学文献中心",
    category: "cn",
    origin: "中国",
    access: "open",
    url: "https://www.ncpssd.org/",
    tags: ["中文库", "社会科学", "免费"],
    description: "国家级哲学社会科学文献平台，免费提供大量中文社科期刊与文献全文检索。",
    descriptionEn: "A national platform offering free full-text search of a large body of Chinese social-science journals and literature."
  },
  {
    id: "duxiu",
    name: "超星读秀",
    category: "cn",
    origin: "中国",
    access: "subscription",
    url: "https://www.duxiu.com/",
    tags: ["中文库", "图书文献", "学术搜索"],
    description: "以图书为核心的中文知识搜索平台，可检索海量图书章节与学术文献（多需机构订阅）。",
    descriptionEn: "A book-centric Chinese knowledge-search platform indexing vast book chapters and academic literature (subscription)."
  },
  {
    id: "connected-papers",
    name: "Connected Papers",
    category: "tool",
    origin: "全球",
    access: "open",
    url: "https://www.connectedpapers.com/",
    tags: ["文献图谱", "可视化探索", "免费"],
    description: "输入一篇论文即生成相关文献关系图，快速把握某议题的经典与前沿脉络。",
    descriptionEn: "Generates a graph of related papers from a single seed paper to quickly map a topic's key and frontier work."
  },
  {
    id: "scite-ai",
    name: "scite.ai",
    category: "tool",
    origin: "美国",
    access: "subscription",
    url: "https://scite.ai/",
    tags: ["引文分析", "智能引用", "文献评估"],
    description: "用「智能引用」标注一篇论文被支持还是被反驳，辅助判断文献可靠性（多需订阅）。",
    descriptionEn: "Uses Smart Citations to show whether a paper is supported or contrasted by citing works, aiding reliability assessment (subscription)."
  }
];

// 城市研究经典书籍：城市研究、城市设计与规划领域的经典著作推荐。
// category: public 公共生活 | theory 城市理论 | form 城市形态 | design 城市设计
// 链接由书名生成豆瓣搜索入口（见 app.js bookUrl）。
const BOOKS = [
  {
    id: "cities-for-people",
    title: "人性化的城市",
    titleEn: "Cities for People",
    author: "扬·盖尔 Jan Gehl",
    year: 2010,
    category: "public",
    tags: ["公共空间", "人的尺度", "城市设计"],
    description: "从人的感官与尺度出发，系统论述如何营造有活力、安全、可持续的人性化城市空间。",
    descriptionEn: "Argues for human-scale cities, showing how to design lively, safe, and sustainable public spaces around people's senses."
  },
  {
    id: "life-between-buildings",
    title: "交往与空间",
    titleEn: "Life Between Buildings",
    author: "扬·盖尔 Jan Gehl",
    year: 1971,
    category: "public",
    tags: ["公共空间", "公共生活", "步行"],
    description: "盖尔的奠基之作，提出建筑之间的户外活动才是城市生活的核心，影响深远。",
    descriptionEn: "Gehl's foundational work arguing that outdoor life between buildings is the essence of urban life."
  },
  {
    id: "social-life-small-urban",
    title: "小城市空间的社会生活",
    titleEn: "The Social Life of Small Urban Spaces",
    author: "威廉·H·怀特 William H. Whyte",
    year: 1980,
    category: "public",
    tags: ["公共空间", "行为观察", "广场"],
    description: "以延时观察记录人在广场与街头的真实行为，用实证方法揭示成功公共空间的规律。",
    descriptionEn: "Uses time-lapse observation of real behavior in plazas and streets to reveal what makes public spaces succeed."
  },
  {
    id: "how-to-study-public-life",
    title: "如何研究公共生活",
    titleEn: "How to Study Public Life",
    author: "扬·盖尔、比吉特·斯瓦尔 Jan Gehl & Birgitte Svarre",
    year: 2013,
    category: "public",
    tags: ["公共生活", "调研方法", "行为观察"],
    description: "系统梳理“公共空间—公共生活”的观察与调研方法，是城市观察与实证研究的方法论指南。",
    descriptionEn: "A methodological guide to observing and studying public life, the toolkit behind public-space/public-life surveys."
  },
  {
    id: "death-and-life",
    title: "美国大城市的死与生",
    titleEn: "The Death and Life of Great American Cities",
    author: "简·雅各布斯 Jane Jacobs",
    year: 1961,
    category: "theory",
    tags: ["城市理论", "城市活力", "社区"],
    description: "对现代主义规划的经典批判，主张多样性、街道眼与混合功能是城市活力与安全的根基。",
    descriptionEn: "A landmark critique of modernist planning, championing diversity, eyes on the street, and mixed use as the basis of urban vitality."
  },
  {
    id: "city-in-history",
    title: "城市发展史",
    titleEn: "The City in History",
    author: "刘易斯·芒福德 Lewis Mumford",
    year: 1961,
    category: "theory",
    tags: ["城市史", "城市理论", "文明"],
    description: "跨越数千年的城市文明通史，探讨城市的起源、演变及其与人类社会的关系。",
    descriptionEn: "A sweeping history of the city across millennia, tracing its origins, evolution, and role in human civilization."
  },
  {
    id: "triumph-of-city",
    title: "城市的胜利",
    titleEn: "Triumph of the City",
    author: "爱德华·格莱泽 Edward Glaeser",
    year: 2011,
    category: "theory",
    tags: ["城市经济", "集聚", "城市理论"],
    description: "从经济学视角论证城市因人的集聚而繁荣，是创新、机遇与可持续的引擎。",
    descriptionEn: "An economist's case that cities thrive on human proximity, driving innovation, opportunity, and sustainability."
  },
  {
    id: "garden-cities",
    title: "明日的田园城市",
    titleEn: "Garden Cities of To-morrow",
    author: "埃比尼泽·霍华德 Ebenezer Howard",
    year: 1902,
    category: "theory",
    tags: ["规划史", "田园城市", "城市理论"],
    description: "提出“田园城市”构想，兼顾城市与乡村之长，深刻影响了现代城市规划的方向。",
    descriptionEn: "Introduces the Garden City ideal combining town and country, profoundly shaping modern town planning."
  },
  {
    id: "image-of-city",
    title: "城市意象",
    titleEn: "The Image of the City",
    author: "凯文·林奇 Kevin Lynch",
    year: 1960,
    category: "form",
    tags: ["城市形态", "城市意象", "认知地图"],
    description: "提出道路、边界、区域、节点、标志物五要素，奠定城市可读性与意象研究的基础。",
    descriptionEn: "Introduces paths, edges, districts, nodes, and landmarks, founding the study of urban legibility and imageability."
  },
  {
    id: "good-city-form",
    title: "城市形态",
    titleEn: "Good City Form",
    author: "凯文·林奇 Kevin Lynch",
    year: 1981,
    category: "form",
    tags: ["城市形态", "规划理论", "城市设计"],
    description: "系统构建评价“好的城市形态”的价值维度与理论框架，是城市设计的重要理论著作。",
    descriptionEn: "Builds a value framework for evaluating what makes good city form, a key theoretical work in urban design."
  },
  {
    id: "collage-city",
    title: "拼贴城市",
    titleEn: "Collage City",
    author: "柯林·罗、弗瑞德·科特 Colin Rowe & Fred Koetter",
    year: 1978,
    category: "form",
    tags: ["城市形态", "城市设计", "城市肌理"],
    description: "批判现代主义乌托邦式规划，主张以“拼贴”方式包容历史层积与多元城市肌理。",
    descriptionEn: "Critiques utopian modernist planning, proposing 'collage' to embrace historical layering and plural urban fabric."
  },
  {
    id: "aesthetic-townscape",
    title: "街道的美学",
    titleEn: "The Aesthetic Townscape",
    author: "芦原义信 Yoshinobu Ashihara",
    year: 1979,
    category: "design",
    tags: ["街道设计", "城市美学", "外部空间"],
    description: "从东西方对比出发，剖析街道、外部空间与建筑边界的美学与尺度关系。",
    descriptionEn: "Analyzes the aesthetics and scale of streets, exterior space, and building edges, comparing East and West."
  },
  {
    id: "pattern-language",
    title: "建筑模式语言",
    titleEn: "A Pattern Language",
    author: "克里斯托弗·亚历山大等 Christopher Alexander et al.",
    year: 1977,
    category: "design",
    tags: ["模式语言", "城市设计", "建成环境"],
    description: "以 253 个从城市到建筑的“模式”，提供营造宜居环境的可组合设计语言。",
    descriptionEn: "Offers 253 composable 'patterns' from city to building scale as a design language for humane environments."
  },
  {
    id: "great-streets",
    title: "伟大的街道",
    titleEn: "Great Streets",
    author: "阿兰·B·雅各布斯 Allan B. Jacobs",
    year: 1993,
    category: "design",
    tags: ["街道设计", "公共空间", "城市设计"],
    description: "通过大量世界街道的实测与图解，归纳出成就“伟大街道”的空间要素与尺度。",
    descriptionEn: "Draws on measured drawings of streets worldwide to distill the spatial elements that make streets great."
  },
  {
    id: "walkable-city",
    title: "适宜步行的城市",
    titleEn: "Walkable City",
    author: "杰夫·斯佩克 Jeff Speck",
    year: 2012,
    category: "design",
    tags: ["步行城市", "街道设计", "可持续"],
    description: "提出“步行性通用理论”，从安全、有趣、舒适、有用四方面推动城市重回步行尺度。",
    descriptionEn: "Presents a 'general theory of walkability', arguing walks must be safe, interesting, comfortable, and useful."
  },
  {
    id: "great-good-place",
    title: "第三空间",
    titleEn: "The Great Good Place",
    author: "雷·奥登伯格 Ray Oldenburg",
    year: 1989,
    category: "public",
    tags: ["公共生活", "第三空间", "社区"],
    description: "提出咖啡馆、酒吧等“第三空间”对社区交往与公共生活的关键价值，影响深远。",
    descriptionEn: "Argues for the vital role of cafés, pubs, and other 'third places' in community and public life."
  },
  {
    id: "happy-city",
    title: "幸福城市",
    titleEn: "Happy City",
    author: "查尔斯·蒙哥马利 Charles Montgomery",
    year: 2013,
    category: "public",
    tags: ["公共生活", "公共健康", "城市设计"],
    description: "结合心理学与城市设计，论证城市形态如何深刻影响居民的幸福感与社会联系。",
    descriptionEn: "Blends psychology and urban design to show how city form shapes residents' happiness and social connection."
  },
  {
    id: "social-justice-city",
    title: "社会正义与城市",
    titleEn: "Social Justice and the City",
    author: "大卫·哈维 David Harvey",
    year: 1973,
    category: "theory",
    tags: ["城市理论", "批判地理", "社会公正"],
    description: "批判城市地理学的奠基之作，从空间与资本视角剖析城市不平等的生成机制。",
    descriptionEn: "A founding text of critical urban geography, analyzing how urban inequality is produced through space and capital."
  },
  {
    id: "economy-of-cities",
    title: "城市经济",
    titleEn: "The Economy of Cities",
    author: "简·雅各布斯 Jane Jacobs",
    year: 1969,
    category: "theory",
    tags: ["城市经济", "城市理论", "集聚"],
    description: "提出城市而非乡村才是经济增长与创新的引擎，重塑了对城市经济作用的认识。",
    descriptionEn: "Argues that cities, not the countryside, are the engines of economic growth and innovation."
  },
  {
    id: "architecture-of-city",
    title: "城市建筑学",
    titleEn: "The Architecture of the City",
    author: "阿尔多·罗西 Aldo Rossi",
    year: 1966,
    category: "form",
    tags: ["城市形态", "类型学", "集体记忆"],
    description: "以类型学与集体记忆解读城市，主张城市是随时间累积的建筑与记忆的产物。",
    descriptionEn: "Reads the city through typology and collective memory, framing it as an artifact built up over time."
  },
  {
    id: "concise-townscape",
    title: "城镇景观",
    titleEn: "The Concise Townscape",
    author: "戈登·卡伦 Gordon Cullen",
    year: 1961,
    category: "form",
    tags: ["城市形态", "序列视景", "城市设计"],
    description: "以“序列视景”方法图解人在城镇中行进的空间体验，奠定城镇景观设计传统。",
    descriptionEn: "Uses 'serial vision' to illustrate the experience of moving through towns, founding the townscape tradition."
  },
  {
    id: "delirious-new-york",
    title: "癫狂的纽约",
    titleEn: "Delirious New York",
    author: "雷姆·库哈斯 Rem Koolhaas",
    year: 1978,
    category: "form",
    tags: ["城市形态", "建筑理论", "城市文化"],
    description: "对曼哈顿“拥挤文化”的回溯性宣言，揭示高密度大都会独特的建筑与城市逻辑。",
    descriptionEn: "A retroactive manifesto for Manhattan's 'culture of congestion', revealing the logic of the dense metropolis."
  },
  {
    id: "design-of-cities",
    title: "城市设计",
    titleEn: "Design of Cities",
    author: "埃德蒙·N·培根 Edmund N. Bacon",
    year: 1967,
    category: "design",
    tags: ["城市设计", "城市空间", "历史案例"],
    description: "借助雅典、罗马、巴黎等历史名城案例，系统讲述城市空间的塑造与设计原理。",
    descriptionEn: "Teaches the shaping of urban space through historic cases such as Athens, Rome, and Paris."
  },
  {
    id: "exterior-design",
    title: "外部空间设计",
    titleEn: "Exterior Design in Architecture",
    author: "芦原义信 Yoshinobu Ashihara",
    year: 1975,
    category: "design",
    tags: ["城市设计", "外部空间", "空间尺度"],
    description: "系统探讨建筑之间外部空间的构成、尺度与围合，是外部空间设计的经典理论。",
    descriptionEn: "A classic on the composition, scale, and enclosure of exterior space between buildings."
  }
];

// 海外城市分析院校申请名单：可申请的院校/实验室，含主导老师与研究方向、申请入口。
// category: apac 亚太 | na 北美 | eu 欧洲
const OVERSEAS_PROGRAMS = [
  {
    id: "hku-urban-analytics",
    school: "香港大学 HKU",
    lab: "城市研究及城市规划中心 CUSUP · 城市分析硕士",
    region: "中国香港",
    category: "apac",
    pi: "叶嘉安 Anthony G.O. Yeh 等",
    url: "https://www.arch.hku.hk/programmes/upad/master-of-science-in-urban-analytics/",
    tags: ["城市分析", "城市数据科学", "GIS"],
    description: "建筑学院城市规划与设计系开设城市分析硕士(MSc Urban Analytics)，依托城市研究及城市规划中心(CUSUP)，方向涵盖城市大数据、GIS 与智慧城市。",
    descriptionEn: "HKU's MSc in Urban Analytics under the Dept of Urban Planning and Design and the CUSUP centre, covering urban big data, GIS, and smart cities."
  },
  {
    id: "nus-ual",
    school: "新加坡国立大学 NUS",
    lab: "Urban Analytics Lab",
    region: "新加坡",
    category: "apac",
    pi: "Filip Biljecki",
    url: "https://ual.sg/",
    tags: ["城市分析", "地理数据科学", "3D城市模型"],
    description: "设计与工程学院建筑系的城市分析实验室，聚焦城市分析、地理空间数据科学与三维城市模型，长期招收博士、研究助理与博士后。",
    descriptionEn: "NUS Architecture's Urban Analytics Lab focused on urban analytics, geospatial data science, and 3D city models; recruits PhDs, RAs, and postdocs."
  },
  {
    id: "polyu-scri-apply",
    school: "香港理工大学 PolyU",
    lab: "Smart Cities Research Institute 智慧城市研究院",
    region: "中国香港",
    category: "apac",
    pi: "研究院多课题组",
    url: "https://www.polyu.edu.hk/scri/",
    tags: ["智慧城市", "城市信息学", "遥感"],
    description: "港理工智慧城市研究院，整合空间信息、城市信息学与智慧城市技术，提供跨学科博士研究机会。",
    descriptionEn: "PolyU's Smart Cities Research Institute integrating geoinformation, urban informatics, and smart-city tech, with interdisciplinary PhD opportunities."
  },
  {
    id: "utokyo-csis",
    school: "东京大学 UTokyo",
    lab: "空间信息科学中心 CSIS",
    region: "日本",
    category: "apac",
    pi: "CSIS 课题组",
    url: "https://www.csis.u-tokyo.ac.jp/en/",
    tags: ["空间数据科学", "GIS", "城市分析"],
    description: "东京大学空间信息科学中心(CSIS)，以空间数据分析、GIS 与城市信息研究见长，提供研究生研究平台。",
    descriptionEn: "The University of Tokyo's Center for Spatial Information Science (CSIS), strong in spatial data analysis, GIS, and urban information research."
  },
  {
    id: "mit-senseable-apply",
    school: "麻省理工学院 MIT",
    lab: "Senseable City Lab",
    region: "美国",
    category: "na",
    pi: "Carlo Ratti",
    url: "https://senseable.mit.edu/",
    tags: ["城市感知", "城市大数据", "城市科学"],
    description: "MIT 可感知城市实验室，用实时数据与传感研究城市活动、移动性与环境，隶属城市研究与规划系(DUSP)。",
    descriptionEn: "MIT's Senseable City Lab studies urban activity, mobility, and environment with real-time sensing; affiliated with DUSP."
  },
  {
    id: "mit-city-science-apply",
    school: "麻省理工学院 MIT",
    lab: "City Science（Media Lab）",
    region: "美国",
    category: "na",
    pi: "Kent Larson",
    url: "https://www.media.mit.edu/groups/city-science/",
    tags: ["城市模型", "城市科学", "出行"],
    description: "MIT 媒体实验室城市科学组，研究城市建模仿真、生活实验室与新型移动性，并在全球设有 City Science Lab 网络。",
    descriptionEn: "MIT Media Lab's City Science group on urban modeling, living labs, and new mobility, with a global network of City Science Labs."
  },
  {
    id: "nyu-cusp-apply",
    school: "纽约大学 NYU",
    lab: "Center for Urban Science + Progress (CUSP)",
    region: "美国",
    category: "na",
    pi: "应用城市科学硕士项目",
    url: "https://cusp.nyu.edu/",
    tags: ["城市信息学", "城市科学", "数据分析"],
    description: "纽约大学城市科学与进步中心，开设应用城市科学与信息学硕士(MS Applied Urban Science and Informatics)，强调数据驱动的城市问题解决。",
    descriptionEn: "NYU's CUSP offers the MS in Applied Urban Science and Informatics, emphasizing data-driven solutions to urban problems."
  },
  {
    id: "uchicago-mansueto-apply",
    school: "芝加哥大学 UChicago",
    lab: "Mansueto Institute for Urban Innovation",
    region: "美国",
    category: "na",
    pi: "Luís Bettencourt",
    url: "https://miurban.uchicago.edu/",
    tags: ["城市科学", "城市理论", "复杂系统"],
    description: "芝加哥大学曼苏埃托城市创新研究所，从城市科学与复杂系统视角研究城市增长、形态与不平等。",
    descriptionEn: "UChicago's Mansueto Institute studies urban growth, form, and inequality through urban science and complex-systems lenses."
  },
  {
    id: "utoronto-school-of-cities-apply",
    school: "多伦多大学 UofT",
    lab: "School of Cities",
    region: "加拿大",
    category: "na",
    pi: "跨学科研究项目",
    url: "https://schoolofcities.utoronto.ca/",
    tags: ["城市研究", "城市数据", "跨学科"],
    description: "多伦多大学城市学院，汇聚跨学科力量研究城市议题，提供城市相关研究生项目与研究机会。",
    descriptionEn: "The University of Toronto's School of Cities convenes interdisciplinary urban research and graduate opportunities."
  },
  {
    id: "ucl-casa-apply",
    school: "伦敦大学学院 UCL",
    lab: "CASA 先进空间分析中心",
    region: "英国",
    category: "eu",
    pi: "Michael Batty 等",
    url: "https://www.ucl.ac.uk/bartlett/casa/",
    tags: ["空间数据科学", "智慧城市", "城市模型"],
    description: "UCL 巴特莱特先进空间分析中心(CASA)，开设城市空间科学硕士(原智慧城市与城市分析)，方向涵盖大数据、城市建模与可视化。",
    descriptionEn: "UCL Bartlett's CASA offers the MSc Urban Spatial Science (formerly Smart Cities & Urban Analytics), spanning big data, modeling, and visualization."
  },
  {
    id: "ethz-fcl-apply",
    school: "苏黎世联邦理工 ETH · 新加坡-ETH中心",
    lab: "Future Cities Lab Global",
    region: "瑞士/新加坡",
    category: "eu",
    pi: "FCL Global 课题组",
    url: "https://fcl.ethz.ch/",
    tags: ["未来城市", "可持续城市", "城市模拟"],
    description: "新加坡-ETH 中心未来城市实验室，跨学科研究高密度城市的可持续设计与仿真，提供博士与博士后研究机会。",
    descriptionEn: "The Singapore-ETH Future Cities Lab researches sustainable design and simulation of dense cities, with PhD and postdoc positions."
  },
  {
    id: "tudelft-uds-apply",
    school: "代尔夫特理工 TU Delft",
    lab: "Urban Data Science · 城市学系",
    region: "荷兰",
    category: "eu",
    pi: "城市学系课题组",
    url: "https://www.tudelft.nl/en/architecture-and-the-built-environment/about-the-faculty/departments/urbanism/organisation/sections/urban-data-science/",
    tags: ["城市数据科学", "GIS", "城市形态"],
    description: "代尔夫特理工建筑与建成环境学院城市学系，设城市数据科学方向，研究城市形态、地理数据与建成环境分析。",
    descriptionEn: "TU Delft Urbanism's Urban Data Science section studies urban form, geodata, and built-environment analysis."
  },
  {
    id: "glasgow-ubdc-apply",
    school: "格拉斯哥大学 Glasgow",
    lab: "Urban Big Data Centre (UBDC)",
    region: "英国",
    category: "eu",
    pi: "UBDC 研究中心",
    url: "https://www.ubdc.ac.uk/",
    tags: ["城市大数据", "数据服务", "城市政策"],
    description: "格拉斯哥大学城市大数据中心，提供城市大数据资源与研究，支持数据驱动的城市政策与社会研究博士项目。",
    descriptionEn: "The University of Glasgow's Urban Big Data Centre offers urban big-data resources and PhD research in data-driven urban policy."
  },
  {
    id: "tsinghua-bcl",
    school: "清华大学 Tsinghua",
    lab: "北京城市实验室 Beijing City Lab",
    region: "中国",
    category: "apac",
    pi: "龙瀛 Ying Long",
    url: "https://www.beijingcitylab.com/",
    tags: ["城市科学", "城市大数据", "城市模型"],
    description: "清华大学建筑学院龙瀛团队发起的北京城市实验室(BCL)，以量化方法与城市大数据研究城市动态、城市模拟与未来城市。",
    descriptionEn: "Beijing City Lab, founded by Ying Long at Tsinghua's School of Architecture, uses quantitative methods and urban big data to study urban dynamics, simulation, and future cities."
  },
  {
    id: "tongji-caup",
    school: "同济大学 Tongji",
    lab: "建筑与城市规划学院 CAUP",
    region: "中国",
    category: "apac",
    pi: "学院多课题组",
    url: "https://caup.tongji.edu.cn/",
    tags: ["城市规划", "城市设计", "城市更新"],
    description: "同济大学建筑与城市规划学院，中国城市规划与设计重镇，研究涵盖城市更新、区域规划与数字化城市设计。",
    descriptionEn: "Tongji's College of Architecture and Urban Planning (CAUP), a leading Chinese school for urban planning and design, spanning renewal, regional planning, and digital urban design."
  },
  {
    id: "cuhk-iofc",
    school: "香港中文大学 CUHK",
    lab: "未来城市研究所 Institute of Future Cities",
    region: "中国香港",
    category: "apac",
    pi: "研究所课题组",
    url: "https://www.iofc.cuhk.edu.hk/",
    tags: ["未来城市", "城市大数据", "跨学科"],
    description: "香港中文大学未来城市研究所，以跨学科方法研究可持续与智慧的未来城市，涵盖城市大数据与社会空间分析。",
    descriptionEn: "CUHK's Institute of Future Cities pursues interdisciplinary research on sustainable, smart future cities, including urban big data and socio-spatial analysis."
  },
  {
    id: "unsw-city-futures",
    school: "新南威尔士大学 UNSW",
    lab: "City Futures Research Centre",
    region: "澳大利亚",
    category: "apac",
    pi: "研究中心多课题组",
    url: "https://cityfutures.ada.unsw.edu.au/",
    tags: ["城市分析", "住房", "城市政策"],
    description: "UNSW 建成环境学院城市未来研究中心，覆盖城市分析、住房、紧凑城市与城市政策，招收博士与硕士研究生。",
    descriptionEn: "UNSW's City Futures Research Centre spans urban analytics, housing, compact cities, and urban policy, recruiting PhD and Masters researchers."
  },
  {
    id: "harvard-gsd-mup",
    school: "哈佛大学 Harvard GSD",
    lab: "城市规划与设计系 · 城市规划硕士(MUP)",
    region: "美国",
    category: "na",
    pi: "城市规划与设计系",
    url: "https://www.gsd.harvard.edu/urban-planning-design/",
    tags: ["城市规划", "城市设计", "城市政策"],
    description: "哈佛设计研究生院城市规划与设计系，开设城市规划硕士(MUP)与城市设计硕士(MAUD)，关注城市与区域的重大议题。",
    descriptionEn: "Harvard GSD's Dept of Urban Planning and Design offers the MUP and MAUD, engaging major urban and regional challenges."
  },
  {
    id: "berkeley-dcrp",
    school: "加州大学伯克利 UC Berkeley",
    lab: "城市与区域规划系 DCRP",
    region: "美国",
    category: "na",
    pi: "城市与区域规划系",
    url: "https://ced.berkeley.edu/city",
    tags: ["城市规划", "城市分析", "社会公正"],
    description: "伯克利环境设计学院城市与区域规划系(DCRP)，提供城市规划硕士与博士，强调规划的社会公平与人本影响。",
    descriptionEn: "UC Berkeley's DCRP offers the MCP and PhD in City and Regional Planning, emphasizing equity and the human impacts of planning."
  },
  {
    id: "gatech-scarp",
    school: "佐治亚理工 Georgia Tech",
    lab: "城市与区域规划学院 SCaRP",
    region: "美国",
    category: "na",
    pi: "学院课题组",
    url: "https://planning.gatech.edu/",
    tags: ["城市规划", "城市信息学", "交通"],
    description: "佐治亚理工城市与区域规划学院，强项包括城市信息学、交通与土地利用、地理空间分析。",
    descriptionEn: "Georgia Tech's School of City and Regional Planning is strong in urban informatics, transportation, and geospatial analysis."
  },
  {
    id: "lse-cities-msc",
    school: "伦敦政治经济学院 LSE",
    lab: "LSE Cities · 城市设计与社会科学硕士",
    region: "英国",
    category: "eu",
    pi: "LSE Cities 研究中心",
    url: "https://www.lse.ac.uk/cities",
    tags: ["城市设计", "城市社会学", "城市政策"],
    description: "伦敦政经 LSE Cities 研究中心，开设城市设计与社会科学硕士，从社会科学视角研究城市治理与城市化。",
    descriptionEn: "LSE Cities offers the MSc City Design and Social Science, studying urban governance and urbanization through a social-science lens."
  },
  {
    id: "polimi-uppd",
    school: "米兰理工 Politecnico di Milano",
    lab: "城市规划与政策设计",
    region: "意大利",
    category: "eu",
    pi: "城市规划项目",
    url: "https://www.polimi.it/en",
    tags: ["城市规划", "城市政策", "区域研究"],
    description: "米兰理工大学城市规划与政策设计项目，聚焦城市与区域规划、政策设计与欧洲城市议题。",
    descriptionEn: "Politecnico di Milano's Urban Planning and Policy Design program focuses on urban and regional planning, policy design, and European urban issues."
  }
];

const EXCLUDED_SAMPLES = [
  "Urban Insight：网页开发机构，不是城市研究实验室。",
  "Jacobs、AECOM、MVRDV、OMA、SOM、Arup：偏设计咨询或建筑事务所，不作为研究来源收录。",
  "CityEngine、Unity、Unreal、UrbanCanvas：偏工具或软件产品，不作为研究机构收录。",
  "单篇 ScienceDirect/Amazon Science 论文：保留期刊或机构入口，不收录单篇文章。",
  "课程、招生、招聘、作品集、AI 工具、数据公司营销页：主题相关性不足或不适合作为资讯源。"
];
