const SOURCES = [
  {
    id: "mit-senseable",
    name: "MIT Senseable City Lab",
    type: "lab",
    region: "美国",
    url: "https://senseable.mit.edu/",
    latestUrl: "https://senseable.mit.edu/news/",
    folder: "城市科学实验室",
    tags: ["城市感知", "数据可视化", "城市科学"],
    description: "MIT 城市数据与感知计算研究实验室，关注城市活动、移动性、环境与实时数据。",
    includeReason: "全球代表性城市科学实验室。"
  },
  {
    id: "mit-city-science",
    name: "MIT City Science",
    type: "lab",
    region: "美国",
    url: "https://www.media.mit.edu/groups/city-science/overview/",
    latestUrl: "https://www.media.mit.edu/groups/city-science/projects/",
    folder: "城市科学实验室",
    tags: ["城市科学", "Media Lab", "未来城市"],
    description: "MIT Media Lab 城市科学小组，聚焦城市系统、计算设计与新型城市生活方式。",
    includeReason: "收藏夹中明确标注为 City Science。"
  },
  {
    id: "mit-city-form",
    name: "MIT City Form Lab",
    type: "lab",
    region: "美国",
    url: "http://cityform.mit.edu/projects",
    latestUrl: "http://cityform.mit.edu/projects",
    folder: "城市科学实验室",
    tags: ["城市形态", "网络分析", "空间模型"],
    description: "关注城市形态、街道网络、可达性和城市空间结构的研究平台。",
    includeReason: "城市形态与空间分析研究来源。"
  },
  {
    id: "harvard-maps",
    name: "Harvard MaP+S Group",
    type: "lab",
    region: "美国",
    url: "https://research.gsd.harvard.edu/maps/about-1/",
    latestUrl: "https://research.gsd.harvard.edu/maps/projects/",
    folder: "城市科学实验室",
    tags: ["空间数据", "建成环境", "地图"],
    description: "Harvard GSD 的建模、分析、原型和系统研究组。",
    includeReason: "城市空间数据与建成环境研究相关。"
  },
  {
    id: "harvard-real",
    name: "Harvard REAL",
    type: "lab",
    region: "美国",
    url: "https://research.gsd.harvard.edu/real/",
    latestUrl: "https://research.gsd.harvard.edu/real/projects/",
    folder: "城市科学实验室",
    tags: ["房地产", "城市经济", "城市数据"],
    description: "Harvard GSD Real Estate and the Built Environment Lab。",
    includeReason: "建成环境和城市经济研究实验室。"
  },
  {
    id: "eth-fcl",
    name: "Future Cities Laboratory",
    type: "lab",
    region: "新加坡/瑞士",
    url: "https://fcl.ethz.ch/",
    latestUrl: "https://fcl.ethz.ch/news.html",
    folder: "城市科学实验室",
    tags: ["未来城市", "可持续城市", "跨学科"],
    description: "ETH Zurich 与新加坡相关研究平台，聚焦未来城市与可持续建成环境。",
    includeReason: "全球领先未来城市研究平台。"
  },
  {
    id: "ucl-casa",
    name: "UCL CASA",
    type: "lab",
    region: "英国",
    url: "https://www.ucl.ac.uk/bartlett/casa/bartlett-centre-advanced-spatial-analysis",
    latestUrl: "https://www.ucl.ac.uk/bartlett/casa/news",
    folder: "城市科学实验室",
    tags: ["空间分析", "城市模型", "数据科学"],
    description: "UCL Bartlett Centre for Advanced Spatial Analysis，城市空间分析代表机构。",
    includeReason: "收藏夹中明确为高级空间分析中心。"
  },
  {
    id: "ual-singapore",
    name: "Urban Analytics Lab Singapore",
    type: "lab",
    region: "新加坡",
    url: "https://ual.sg/",
    latestUrl: "https://ual.sg/research/",
    folder: "城市科学实验室",
    tags: ["城市分析", "亚洲城市", "计算城市"],
    description: "新加坡城市分析实验室，关注城市数据、计算方法与亚洲城市问题。",
    includeReason: "收藏夹中明确为 Urban Analytics Lab。"
  },
  {
    id: "beijing-city-lab",
    name: "Beijing City Lab",
    type: "lab",
    region: "中国",
    url: "https://www.beijingcitylab.com/",
    latestUrl: "https://www.beijingcitylab.com/publications/",
    folder: "城市科学实验室",
    tags: ["中国城市", "开放数据", "城市模型"],
    description: "面向中国城市研究的开放数据、论文与城市分析平台。",
    includeReason: "城市实验室与研究成果长期更新。"
  },
  {
    id: "hku-dil",
    name: "HKU Data Intelligence Lab",
    type: "lab",
    region: "中国香港",
    url: "https://sites.google.com/view/chaoh/group-join-us",
    latestUrl: "https://sites.google.com/view/chaoh/publications",
    folder: "城市科学实验室",
    tags: ["智慧城市", "数据智能", "城市分析"],
    description: "香港大学智慧城市与数据智能相关研究团队。",
    includeReason: "收藏夹标注为 HKU 智慧城市实验室。"
  },
  {
    id: "tudelft-uds",
    name: "TU Delft Urban Data Science",
    type: "lab",
    region: "荷兰",
    url: "https://www.tudelft.nl/en/architecture-and-the-built-environment/about-the-faculty/departments/urbanism/organisation/sections/urban-data-science/",
    latestUrl: "https://www.tudelft.nl/en/architecture-and-the-built-environment/about-the-faculty/departments/urbanism/organisation/sections/urban-data-science/",
    folder: "城市科学实验室",
    tags: ["城市数据科学", "城市规划", "计算方法"],
    description: "代尔夫特理工城市数据科学方向，连接城市规划与计算方法。",
    includeReason: "收藏夹中明确为城市数据科学实验室。"
  },
  {
    id: "tudelft-urban-studies",
    name: "TU Delft Urban Studies",
    type: "lab",
    region: "荷兰",
    url: "https://www.tudelft.nl/en/architecture-and-the-built-environment/about-the-faculty/departments/urbanism/organisation/sections/urban-studies",
    latestUrl: "https://www.tudelft.nl/en/architecture-and-the-built-environment/about-the-faculty/departments/urbanism/organisation/sections/urban-studies",
    folder: "城市科学实验室",
    tags: ["城市研究", "规划理论", "城市化"],
    description: "TU Delft 城市研究方向，关注城市化、规划和空间转型。",
    includeReason: "城市研究学术机构。"
  },
  {
    id: "ams-institute",
    name: "AMS Institute",
    type: "institution",
    region: "荷兰",
    url: "https://www.ams-institute.org/",
    latestUrl: "https://www.ams-institute.org/news/",
    folder: "城市科学实验室",
    tags: ["城市创新", "可持续城市", "应用研究"],
    description: "Amsterdam Institute for Advanced Metropolitan Solutions，连接城市研究与应用创新。",
    includeReason: "收藏夹中阿姆斯特丹城市研究机构。"
  },
  {
    id: "shanghai-global-city",
    name: "上海全球城市研究院",
    type: "institution",
    region: "中国",
    url: "http://sigc.shnu.edu.cn/main.htm",
    latestUrl: "http://sigc.shnu.edu.cn/main.htm",
    folder: "城市研究机构",
    tags: ["全球城市", "长三角", "城市网络"],
    description: "围绕全球城市、城市网络和区域一体化开展研究。",
    includeReason: "收藏夹中明确为城市研究院。"
  },
  {
    id: "bjghy",
    name: "北京市城市规划设计研究院",
    type: "institution",
    region: "中国",
    url: "https://www.bjghy.com.cn/cont/21",
    latestUrl: "https://www.bjghy.com.cn/",
    folder: "城市研究机构",
    tags: ["规划研究", "北京", "城市治理"],
    description: "北京城市规划与城市治理研究、设计和政策支撑机构。",
    includeReason: "规划研究机构，保留为城市研究来源。"
  },
  {
    id: "thupdi",
    name: "北京清华同衡规划设计研究院",
    type: "institution",
    region: "中国",
    url: "http://www.thupdi.com/",
    latestUrl: "http://www.thupdi.com/",
    folder: "城市研究机构",
    tags: ["规划研究", "城市更新", "空间治理"],
    description: "规划设计研究机构，覆盖城市更新、空间治理与区域研究。",
    includeReason: "城市规划研究机构。"
  },
  {
    id: "thupdi-ict",
    name: "清华同衡技术创新中心",
    type: "institution",
    region: "中国",
    url: "http://ict.thupdi.com/",
    latestUrl: "http://ict.thupdi.com/",
    folder: "城市研究机构",
    tags: ["技术创新", "城市数据", "规划工具"],
    description: "聚焦规划技术创新、城市数据与数字化工具。",
    includeReason: "技术型城市研究与规划创新来源。"
  },
  {
    id: "icity-design",
    name: "万科城市研究院",
    type: "institution",
    region: "中国",
    url: "https://www.icity.design/about",
    latestUrl: "https://www.icity.design/",
    folder: "城市研究机构",
    tags: ["城市研究", "社区", "生活方式"],
    description: "围绕城市、社区和居住生活方式开展研究与议题传播。",
    includeReason: "收藏夹中明确为城市研究院。"
  },
  {
    id: "wri-china",
    name: "WRI China",
    type: "institution",
    region: "中国/全球",
    url: "https://wri.org.cn/",
    latestUrl: "https://wri.org.cn/insights",
    folder: "城市研究机构",
    tags: ["可持续城市", "气候", "交通"],
    description: "世界资源研究所中国办公室，长期发布城市、交通、气候与可持续发展研究。",
    includeReason: "可持续城市与政策研究机构。"
  },
  {
    id: "nacto",
    name: "NACTO",
    type: "institution",
    region: "美国/全球",
    url: "https://nacto.org/publication/transit-street-design-guide/",
    latestUrl: "https://nacto.org/publications/",
    folder: "城市研究机构",
    tags: ["街道设计", "交通", "公共空间"],
    description: "城市交通官员协会，发布街道设计、公交街道和城市交通指南。",
    includeReason: "城市交通与街道研究实践指南来源。"
  },
  {
    id: "itdp-china",
    name: "ITDP China",
    type: "institution",
    region: "中国/全球",
    url: "http://www.itdp-china.org/",
    latestUrl: "http://www.itdp-china.org/",
    folder: "城市研究机构",
    tags: ["可持续交通", "TOD", "低碳城市"],
    description: "交通与发展政策研究所中国，关注可持续交通、公交、步行与低碳城市。",
    includeReason: "城市交通政策研究机构。"
  },
  {
    id: "pps",
    name: "Project for Public Spaces",
    type: "institution",
    region: "美国/全球",
    url: "https://www.pps.org/our-team",
    latestUrl: "https://www.pps.org/articles",
    folder: "城市研究机构",
    tags: ["公共空间", "场所营造", "社区"],
    description: "公共空间与场所营造非营利研究和实践组织。",
    includeReason: "收藏夹中城市公共空间非盈利研究组织。"
  },
  {
    id: "china-stc",
    name: "宇恒可持续交通研究中心",
    type: "institution",
    region: "中国",
    url: "http://www.chinastc.org/gywm",
    latestUrl: "http://www.chinastc.org/",
    folder: "城市研究机构",
    tags: ["可持续交通", "城市交通", "低碳"],
    description: "关注可持续交通、城市交通政策与低碳出行的研究中心。",
    includeReason: "收藏夹中标注为可持续交通研究中心。"
  },
  {
    id: "src-street",
    name: "SRC 城市街景设计研究中心",
    type: "institution",
    region: "中国",
    url: "http://www.streetsrc.com/",
    latestUrl: "http://www.streetsrc.com/",
    folder: "城市研究机构",
    tags: ["街景", "街道设计", "城市品质"],
    description: "围绕城市街景、街道空间和设计研究的机构。",
    includeReason: "城市街景研究相关。"
  },
  {
    id: "ura-singapore",
    name: "URA Singapore Publications",
    type: "institution",
    region: "新加坡",
    url: "https://www.ura.gov.sg/Corporate/Resources/Publications",
    latestUrl: "https://www.ura.gov.sg/Corporate/Resources/Publications",
    folder: "城市研究机构",
    tags: ["城市规划", "新加坡", "政策出版"],
    description: "新加坡市区重建局出版物入口，可跟踪城市规划政策和研究资料。",
    includeReason: "官方城市规划出版物来源。"
  },
  {
    id: "nyu-cusp",
    name: "NYU Center for Urban Science and Progress",
    type: "institution",
    region: "美国",
    url: "https://cusp.nyu.edu/",
    latestUrl: "https://cusp.nyu.edu/research/",
    folder: "全球城市研究机构",
    tags: ["城市科学", "城市信息学", "数据科学"],
    description: "纽约大学城市科学与进步中心，围绕城市信息学、城市数据与应用城市科学开展教学和研究。",
    includeReason: "全球城市科学与城市信息学代表性研究中心。"
  },
  {
    id: "nyu-marron",
    name: "NYU Marron Institute of Urban Management",
    type: "institution",
    region: "美国",
    url: "https://marroninstitute.nyu.edu/",
    latestUrl: "https://marroninstitute.nyu.edu/blog",
    folder: "全球城市研究机构",
    tags: ["城市管理", "应用研究", "政策"],
    description: "纽约大学城市管理研究院，关注城市治理、交通与土地利用、健康环境和城市扩张等应用研究。",
    includeReason: "应用城市研究和城市政策项目长期更新。"
  },
  {
    id: "penn-iur",
    name: "Penn Institute for Urban Research",
    type: "institution",
    region: "美国",
    url: "https://penniur.upenn.edu/",
    latestUrl: "https://penniur.upenn.edu/news/",
    folder: "全球城市研究机构",
    tags: ["城市研究", "可持续城市", "政策"],
    description: "宾夕法尼亚大学跨学科城市研究机构，关注城市发展、包容性和可持续城市议题。",
    includeReason: "高校城市研究中心和全球城市研究网络入口。"
  },
  {
    id: "uchicago-mansueto",
    name: "Mansueto Institute for Urban Innovation",
    type: "institution",
    region: "美国",
    url: "https://miurban.uchicago.edu/",
    latestUrl: "https://miurban.uchicago.edu/news/",
    folder: "全球城市研究机构",
    tags: ["城市创新", "城市政策", "研究资助"],
    description: "芝加哥大学城市创新研究平台，支持城市议题研究、训练、项目和公共活动。",
    includeReason: "城市创新与城市政策研究来源。"
  },
  {
    id: "nyu-urban-systems-lab",
    name: "Urban Systems Lab",
    type: "lab",
    region: "美国/全球",
    url: "https://urbansystemslab.com/",
    latestUrl: "https://urbansystemslab.com/news",
    folder: "城市科学实验室",
    tags: ["城市韧性", "气候风险", "自然基解决方案"],
    description: "面向宜居城市的城市系统实验室，研究城市韧性、气候适应和社会生态系统。",
    includeReason: "全球城市韧性和气候适应研究实验室。"
  },
  {
    id: "columbia-csr",
    name: "Columbia Center for Spatial Research",
    type: "institution",
    region: "美国",
    url: "https://c4sr.columbia.edu/",
    latestUrl: "https://c4sr.columbia.edu/news",
    folder: "全球城市研究机构",
    tags: ["空间研究", "制图", "数据可视化"],
    description: "哥伦比亚大学空间研究中心，连接建筑、城市主义、人文和数据科学。",
    includeReason: "空间数据、城市制图和批判性城市研究平台。"
  },
  {
    id: "bari",
    name: "Boston Area Research Initiative",
    type: "institution",
    region: "美国",
    url: "https://cssh.northeastern.edu/bari/",
    latestUrl: "https://cssh.northeastern.edu/bari/news/",
    folder: "全球城市研究机构",
    tags: ["城市数据", "社区", "城市治理"],
    description: "波士顿区域研究计划，使用城市数据连接社区、政策和学术研究。",
    includeReason: "城市数据治理和城市社会研究案例库。"
  },
  {
    id: "cmu-metro21",
    name: "Metro21: Smart Cities Institute",
    type: "institution",
    region: "美国",
    url: "https://www.cmu.edu/metro21/",
    latestUrl: "https://www.cmu.edu/metro21/news/",
    folder: "全球城市研究机构",
    tags: ["智慧城市", "交通", "社区技术"],
    description: "卡内基梅隆大学智慧城市研究与实施中心，连接技术研究、社区合作和政策落地。",
    includeReason: "智慧城市和城市技术应用研究来源。"
  },
  {
    id: "lse-cities",
    name: "LSE Cities",
    type: "institution",
    region: "英国/全球",
    url: "https://www.lse.ac.uk/cities",
    latestUrl: "https://www.lse.ac.uk/cities/news",
    folder: "全球城市研究机构",
    tags: ["全球城市", "城市治理", "城市可持续"],
    description: "伦敦政治经济学院国际城市研究中心，研究 21 世纪城市的社会、空间和环境复杂性。",
    includeReason: "全球城市治理、城市可持续和 Urban Age 研究来源。"
  },
  {
    id: "ubdc",
    name: "Urban Big Data Centre",
    type: "institution",
    region: "英国",
    url: "https://www.ubdc.ac.uk/",
    latestUrl: "https://www.ubdc.ac.uk/news-events/",
    folder: "全球城市研究机构",
    tags: ["城市大数据", "数据服务", "城市分析"],
    description: "格拉斯哥大学城市大数据中心，提供城市智能数据服务、研究主题和数据目录。",
    includeReason: "城市大数据、交通、住房、劳动力和环境数据研究平台。"
  },
  {
    id: "hcu-city-science-lab",
    name: "CityScienceLab Hamburg",
    type: "lab",
    region: "德国",
    url: "https://www.hcu-hamburg.de/en/research/citysciencelab",
    latestUrl: "https://www.hcu-hamburg.de/en/research/citysciencelab/news",
    folder: "城市科学实验室",
    tags: ["城市科学", "数字城市", "城市模拟"],
    description: "汉堡 HafenCity University 与 MIT Media Lab 相关的城市科学实验室，关注数字化背景下的城市挑战。",
    includeReason: "欧洲城市科学、城市模拟和数字城市研究来源。"
  },
  {
    id: "school-of-cities",
    name: "University of Toronto School of Cities",
    type: "institution",
    region: "加拿大",
    url: "https://schoolofcities.utoronto.ca/",
    latestUrl: "https://schoolofcities.utoronto.ca/research-publications/",
    folder: "全球城市研究机构",
    tags: ["城市研究", "城市数据", "跨学科"],
    description: "多伦多大学城市学院，围绕城市研究、教育和参与建立跨学科平台。",
    includeReason: "北美跨学科城市研究和城市数据项目来源。"
  },
  {
    id: "african-centre-cities",
    name: "African Centre for Cities",
    type: "institution",
    region: "南非/非洲",
    url: "https://www.africancentreforcities.net/",
    latestUrl: "https://www.africancentreforcities.net/research/",
    folder: "全球城市研究机构",
    tags: ["非洲城市", "全球南方", "可持续城市"],
    description: "开普敦大学非洲城市中心，开展全球南方视角下的应用城市研究、教学和公共传播。",
    includeReason: "非洲城市研究和全球南方城市议题核心来源。"
  },
  {
    id: "iihs",
    name: "Indian Institute for Human Settlements",
    type: "institution",
    region: "印度",
    url: "https://iihs.co.in/",
    latestUrl: "https://iihs.co.in/research/",
    folder: "全球城市研究机构",
    tags: ["人居环境", "城市化", "南亚城市"],
    description: "印度人居环境研究与教育机构，覆盖城市化研究、实验室、实践项目和 Urbanisation 期刊。",
    includeReason: "南亚城市化、人居环境和城市政策研究来源。"
  },
  {
    id: "cedeus",
    name: "CEDEUS",
    type: "institution",
    region: "智利/拉美",
    url: "https://www.cedeus.cl/",
    latestUrl: "https://www.cedeus.cl/noticias/",
    folder: "全球城市研究机构",
    tags: ["可持续城市", "拉美城市", "城市观测"],
    description: "智利可持续城市发展中心，联合高校开展城市可持续、城市观测和政策转化。",
    includeReason: "拉美可持续城市研究和观测平台。"
  },
  {
    id: "observatorio-metropoles",
    name: "Observatório das Metrópoles",
    type: "institution",
    region: "巴西",
    url: "https://www.observatoriodasmetropoles.net.br/",
    latestUrl: "https://www.observatoriodasmetropoles.net.br/noticias/",
    folder: "全球城市研究机构",
    tags: ["都市圈", "城市不平等", "巴西城市"],
    description: "巴西都市圈观测研究网络，覆盖大都市治理、社会空间不平等和城市公共政策。",
    includeReason: "拉美都市圈研究和南南合作资料入口。"
  },
  {
    id: "polyu-scri",
    name: "PolyU Smart Cities Research Institute",
    type: "institution",
    region: "中国香港",
    url: "https://www.polyu.edu.hk/scri/",
    latestUrl: "https://www.polyu.edu.hk/scri/news-and-events/news/",
    folder: "全球城市研究机构",
    tags: ["智慧城市", "城市信息学", "大湾区"],
    description: "香港理工大学智慧城市研究院，聚焦城市信息学、智慧交通、智慧环境、治理和经济。",
    includeReason: "亚洲智慧城市与城市信息学研究平台。"
  },
  {
    id: "nature-cities",
    name: "Nature Cities",
    type: "journal",
    region: "全球",
    url: "https://www.nature.com/natcities/",
    latestUrl: "https://www.nature.com/natcities/research-articles",
    folder: "城市研究期刊",
    tags: ["综合城市研究", "Nature", "论文"],
    description: "Nature Portfolio 城市研究期刊，覆盖城市科学、城市政策与可持续城市议题。",
    includeReason: "收藏夹中明确为自然城市期刊。"
  },
  {
    id: "cities",
    name: "Cities",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/cities",
    latestUrl: "https://www.sciencedirect.com/journal/cities/issues",
    folder: "城市研究期刊",
    issn: ["0264-2751"],
    tags: ["城市研究", "城市政策", "论文"],
    description: "Elsevier 城市研究期刊，关注城市政策、城市化与空间发展。",
    includeReason: "核心城市研究期刊。"
  },
  {
    id: "ceus",
    name: "Computers, Environment and Urban Systems",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/computers-environment-and-urban-systems",
    latestUrl: "https://www.sciencedirect.com/journal/computers-environment-and-urban-systems/issues",
    folder: "城市研究期刊",
    issn: ["0198-9715"],
    tags: ["城市系统", "计算方法", "GIS"],
    description: "城市系统、计算、GIS、环境与城市数据方法相关期刊。",
    includeReason: "计算城市研究关键期刊。"
  },
  {
    id: "sustainable-cities",
    name: "Sustainable Cities and Society",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/sustainable-cities-and-society",
    latestUrl: "https://www.sciencedirect.com/journal/sustainable-cities-and-society/issues",
    folder: "城市研究期刊",
    issn: ["2210-6707"],
    tags: ["可持续城市", "社会", "论文"],
    description: "关注可持续城市、气候、能源、社会与建成环境的期刊。",
    includeReason: "可持续城市研究核心期刊。"
  },
  {
    id: "landscape-urban-planning",
    name: "Landscape and Urban Planning",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/landscape-and-urban-planning",
    latestUrl: "https://www.sciencedirect.com/journal/landscape-and-urban-planning/issues",
    folder: "城市研究期刊",
    issn: ["0169-2046"],
    tags: ["景观", "城市规划", "生态"],
    description: "景观、城市规划、生态系统服务和空间规划研究期刊。",
    includeReason: "城市与景观规划核心期刊。"
  },
  {
    id: "epb",
    name: "Environment and Planning B",
    type: "journal",
    region: "全球",
    url: "https://journals.sagepub.com/home/epb",
    latestUrl: "https://journals.sagepub.com/toc/EPB/current",
    folder: "城市研究期刊",
    issn: ["2399-8083", "2399-8091"],
    tags: ["城市分析", "城市科学", "空间计算"],
    description: "Environment and Planning B: Urban Analytics and City Science。",
    includeReason: "城市分析与城市科学代表期刊。"
  },
  {
    id: "urban-research-practice",
    name: "Urban Research & Practice",
    type: "journal",
    region: "全球",
    url: "https://www.tandfonline.com/toc/rurp20/current",
    latestUrl: "https://www.tandfonline.com/toc/rurp20/current",
    folder: "城市研究期刊",
    issn: ["1753-5069", "1753-5077"],
    tags: ["城市研究", "实践", "政策"],
    description: "连接城市研究、政策与实践的 Taylor & Francis 期刊。",
    includeReason: "收藏夹中明确为 Urban Research & Practice。"
  },
  {
    id: "city-community",
    name: "City & Community",
    type: "journal",
    region: "全球",
    url: "https://onlinelibrary.wiley.com/journal/15406040",
    latestUrl: "https://onlinelibrary.wiley.com/journal/15406040",
    folder: "城市研究期刊",
    issn: ["1540-6040", "1535-6841"],
    tags: ["城市社会学", "社区", "论文"],
    description: "城市社会学、社区和城市社会研究相关期刊。",
    includeReason: "收藏夹中城市与社区期刊。"
  },
  {
    id: "arxiv-cs-cy",
    name: "arXiv Computer and Society",
    type: "journal",
    region: "全球",
    url: "https://arxiv.org/list/cs.CY/recent?skip=0&show=25",
    latestUrl: "https://arxiv.org/list/cs.CY/recent?skip=0&show=25",
    folder: "城市研究期刊",
    feed: "https://export.arxiv.org/api/query?search_query=cat:cs.CY&start=0&max_results=8&sortBy=submittedDate&sortOrder=descending",
    feedKind: "atom",
    tags: ["预印本", "计算社会", "论文"],
    description: "计算机与社会方向预印本入口，可捕捉城市计算与社会技术研究信号。",
    includeReason: "可作为城市计算相关预印本监测入口。"
  },
  {
    id: "topos",
    name: "Topos Magazine",
    type: "journal",
    region: "全球",
    url: "https://toposmagazine.com/",
    latestUrl: "https://toposmagazine.com/",
    folder: "城市研究期刊",
    tags: ["景观", "城市主义", "杂志"],
    description: "景观建筑与城市主义国际评论平台。",
    includeReason: "收藏夹中城市与景观相关出版平台。"
  },
  {
    id: "scenario",
    name: "Scenario Journal",
    type: "journal",
    region: "全球",
    url: "https://scenariojournal.com/strategies/",
    latestUrl: "https://scenariojournal.com/",
    folder: "城市研究期刊",
    tags: ["景观城市主义", "设计研究", "期刊"],
    description: "景观、生态与城市主义设计研究期刊。",
    includeReason: "收藏夹中设计研究期刊平台。"
  },
  {
    id: "springer-urban-studies",
    name: "Springer Urban Studies Series",
    type: "journal",
    region: "全球",
    url: "https://www.springer.com/series/16474/books",
    latestUrl: "https://www.springer.com/series/16474/books",
    folder: "城市研究期刊",
    tags: ["出版系列", "城市研究", "图书"],
    description: "Springer 城市研究系列图书入口。",
    includeReason: "虽非期刊，但属于城市研究出版系列，归入出版资源。"
  },
  {
    id: "urban-studies",
    name: "Urban Studies",
    type: "journal",
    region: "全球",
    url: "https://journals.sagepub.com/home/usj",
    latestUrl: "https://journals.sagepub.com/home/usj",
    folder: "城市研究期刊",
    issn: ["0042-0980", "1360-063X"],
    tags: ["综合城市研究", "城市理论", "社会科学"],
    description: "国际同行评审城市研究期刊，覆盖城市状况、城市区域变化和跨学科城市社会科学研究。",
    includeReason: "全球城市研究核心期刊。"
  },
  {
    id: "ijurr",
    name: "International Journal of Urban and Regional Research",
    type: "journal",
    region: "全球",
    url: "https://onlinelibrary.wiley.com/journal/14682427",
    latestUrl: "https://onlinelibrary.wiley.com/journal/14682427",
    folder: "城市研究期刊",
    issn: ["0309-1317", "1468-2427"],
    tags: ["城市研究", "区域研究", "城市理论"],
    description: "IJURR，关注城市与区域研究、城市理论、全球城市化和社会空间转型。",
    includeReason: "城市与区域研究国际核心期刊。"
  },
  {
    id: "journal-urban-affairs",
    name: "Journal of Urban Affairs",
    type: "journal",
    region: "全球",
    url: "https://www.tandfonline.com/journals/ujua20",
    latestUrl: "https://www.tandfonline.com/toc/ujua20/current",
    folder: "城市研究期刊",
    issn: ["0735-2166", "1467-9906"],
    tags: ["城市政策", "城市事务", "治理"],
    description: "Urban Affairs Association 相关期刊，关注城市政策、城市治理、社区和城市发展。",
    includeReason: "城市事务与城市政策研究期刊。"
  },
  {
    id: "urban-geography",
    name: "Urban Geography",
    type: "journal",
    region: "全球",
    url: "https://www.tandfonline.com/journals/rurb20",
    latestUrl: "https://www.tandfonline.com/toc/rurb20/current",
    folder: "城市研究期刊",
    issn: ["0272-3638", "1938-2847"],
    tags: ["城市地理", "空间不平等", "城市政策"],
    description: "城市地理学期刊，覆盖城市政策、规划、住房、贫困、族群和城市经济活动。",
    includeReason: "城市地理与城市空间研究核心来源。"
  },
  {
    id: "journal-urban-technology",
    name: "Journal of Urban Technology",
    type: "journal",
    region: "全球",
    url: "https://www.tandfonline.com/journals/cjut20",
    latestUrl: "https://www.tandfonline.com/toc/cjut20/current",
    folder: "城市研究期刊",
    issn: ["1063-0732", "1466-1853"],
    tags: ["城市技术", "智慧城市", "城市信息学"],
    description: "关注城市技术、智慧城市、信息基础设施和城市社会技术系统的期刊。",
    includeReason: "城市技术和智慧城市研究期刊。"
  },
  {
    id: "journal-urban-design",
    name: "Journal of Urban Design",
    type: "journal",
    region: "全球",
    url: "https://www.tandfonline.com/journals/cjud20",
    latestUrl: "https://www.tandfonline.com/toc/cjud20/current",
    folder: "城市研究期刊",
    issn: ["1357-4809", "1469-9664"],
    tags: ["城市设计", "建成环境", "公共空间"],
    description: "聚焦城市设计理论、方法、实践和建成环境品质的国际期刊。",
    includeReason: "城市设计研究核心期刊。"
  },
  {
    id: "journal-planning-education-research",
    name: "Journal of Planning Education and Research",
    type: "journal",
    region: "全球",
    url: "https://journals.sagepub.com/home/jpe",
    latestUrl: "https://journals.sagepub.com/home/jpe",
    folder: "城市研究期刊",
    issn: ["0739-456X", "1552-6577"],
    tags: ["城市规划", "规划教育", "规划研究"],
    description: "规划教育与规划研究期刊，覆盖城市规划理论、方法、实践和教育。",
    includeReason: "城市规划学术研究和方法来源。"
  },
  {
    id: "journal-planning-literature",
    name: "Journal of Planning Literature",
    type: "journal",
    region: "全球",
    url: "https://journals.sagepub.com/home/jpl",
    latestUrl: "https://journals.sagepub.com/home/jpl",
    folder: "城市研究期刊",
    issn: ["0885-4122", "1552-6593"],
    tags: ["城市规划", "文献综述", "理论"],
    description: "规划领域综述型期刊，用于追踪城市规划、土地利用和政策研究的知识脉络。",
    includeReason: "适合作为城市规划研究综述入口。"
  },
  {
    id: "environment-urbanization",
    name: "Environment and Urbanization",
    type: "journal",
    region: "全球南方",
    url: "https://journals.sagepub.com/home/eau",
    latestUrl: "https://journals.sagepub.com/home/eau",
    folder: "城市研究期刊",
    issn: ["0956-2478", "1746-0301"],
    tags: ["全球南方", "城市贫困", "环境"],
    description: "关注非洲、亚洲和拉美城市环境、城市贫困、住房和可持续发展的期刊。",
    includeReason: "全球南方城市与环境议题核心来源。"
  },
  {
    id: "environment-urbanization-asia",
    name: "Environment and Urbanization ASIA",
    type: "journal",
    region: "亚洲",
    url: "https://journals.sagepub.com/home/eua",
    latestUrl: "https://journals.sagepub.com/home/eua",
    folder: "城市研究期刊",
    issn: ["0975-4253", "0976-3546"],
    tags: ["亚洲城市", "城市环境", "发展"],
    description: "聚焦亚洲城市化、城市环境、基础设施和发展政策的期刊。",
    includeReason: "亚洲城市与环境研究来源。"
  },
  {
    id: "european-urban-regional-studies",
    name: "European Urban and Regional Studies",
    type: "journal",
    region: "欧洲",
    url: "https://journals.sagepub.com/home/eur",
    latestUrl: "https://journals.sagepub.com/home/eur",
    folder: "城市研究期刊",
    issn: ["0969-7764", "1461-7145"],
    tags: ["欧洲城市", "区域研究", "城市政策"],
    description: "关注欧洲城市与区域发展、城市政策、经济和社会空间变化的期刊。",
    includeReason: "欧洲城市与区域研究核心期刊。"
  },
  {
    id: "urban-climate",
    name: "Urban Climate",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/urban-climate",
    latestUrl: "https://www.sciencedirect.com/journal/urban-climate/issues",
    folder: "城市研究期刊",
    issn: ["2212-0955"],
    tags: ["城市气候", "热环境", "韧性"],
    description: "聚焦城市气候、热岛、气候适应、城市环境建模和气候韧性的期刊。",
    includeReason: "城市气候与城市韧性研究期刊。"
  },
  {
    id: "urban-ecosystems",
    name: "Urban Ecosystems",
    type: "journal",
    region: "全球",
    url: "https://link.springer.com/journal/11252",
    latestUrl: "https://link.springer.com/journal/11252/volumes-and-issues",
    folder: "城市研究期刊",
    issn: ["1083-8155", "1573-1642"],
    tags: ["城市生态", "生态系统", "生物多样性"],
    description: "研究城市生态系统、城市生物多样性、生态过程和人类活动影响的期刊。",
    includeReason: "城市生态研究核心期刊。"
  },
  {
    id: "urban-forestry-greening",
    name: "Urban Forestry & Urban Greening",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/urban-forestry-and-urban-greening",
    latestUrl: "https://www.sciencedirect.com/journal/urban-forestry-and-urban-greening/issues",
    folder: "城市研究期刊",
    issn: ["1618-8667"],
    tags: ["城市林业", "绿地", "生态服务"],
    description: "关注城市林业、城市绿化、城市绿地管理和生态系统服务的期刊。",
    includeReason: "城市绿地和自然基解决方案研究来源。"
  },
  {
    id: "journal-transport-geography",
    name: "Journal of Transport Geography",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/journal-of-transport-geography",
    latestUrl: "https://www.sciencedirect.com/journal/journal-of-transport-geography/issues",
    folder: "城市研究期刊",
    issn: ["0966-6923"],
    tags: ["交通地理", "出行", "空间结构"],
    description: "交通地理学期刊，覆盖出行、可达性、交通政策与城市空间结构。",
    includeReason: "城市交通与空间可达性研究来源。"
  },
  {
    id: "land-use-policy",
    name: "Land Use Policy",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/land-use-policy",
    latestUrl: "https://www.sciencedirect.com/journal/land-use-policy/issues",
    folder: "城市研究期刊",
    issn: ["0264-8377"],
    tags: ["土地利用", "空间政策", "规划治理"],
    description: "关注土地利用、空间政策、城市扩张和规划治理的跨学科期刊。",
    includeReason: "土地利用与城市空间政策研究来源。"
  },
  {
    id: "city-journal",
    name: "City",
    type: "journal",
    region: "全球",
    url: "https://www.tandfonline.com/journals/ccit20",
    latestUrl: "https://www.tandfonline.com/toc/ccit20/current",
    folder: "城市研究期刊",
    issn: ["1360-4813", "1470-3629"],
    tags: ["城市理论", "城市变化", "批判城市研究"],
    description: "City: analysis of urban change, theory, action，关注城市变化、理论和行动导向研究。",
    includeReason: "批判城市研究和城市理论来源。"
  },
  {
    id: "journal-urban-history",
    name: "Journal of Urban History",
    type: "journal",
    region: "全球",
    url: "https://journals.sagepub.com/home/juh",
    latestUrl: "https://journals.sagepub.com/home/juh",
    folder: "城市研究期刊",
    issn: ["0096-1442", "1552-6771"],
    tags: ["城市史", "历史城市", "社会史"],
    description: "城市史国际期刊，关注城市历史、城市社会和历史空间过程。",
    includeReason: "城市历史研究来源。"
  },
  {
    id: "housing-studies",
    name: "Housing Studies",
    type: "journal",
    region: "全球",
    url: "https://www.tandfonline.com/journals/chos20",
    latestUrl: "https://www.tandfonline.com/toc/chos20/current",
    folder: "城市研究期刊",
    issn: ["0267-3037", "1466-1810"],
    tags: ["住房", "社区", "城市政策"],
    description: "住房研究期刊，覆盖住房政策、住房市场、居住公平和城市社会问题。",
    includeReason: "城市住房与居住政策研究期刊。"
  },
  {
    id: "urban-planning-cogitatio",
    name: "Urban Planning",
    type: "journal",
    region: "全球",
    url: "https://www.cogitatiopress.com/urbanplanning",
    latestUrl: "https://www.cogitatiopress.com/urbanplanning/issue/current",
    folder: "城市研究期刊",
    issn: ["2183-7635"],
    tags: ["开放获取", "城市规划", "城市治理"],
    description: "开放获取城市规划期刊，关注城市治理、规划理论、空间转型和可持续城市。",
    includeReason: "开放获取城市规划研究来源。"
  },
  {
    id: "journal-urban-management",
    name: "Journal of Urban Management",
    type: "journal",
    region: "全球",
    url: "https://www.sciencedirect.com/journal/journal-of-urban-management",
    latestUrl: "https://www.sciencedirect.com/journal/journal-of-urban-management/issues",
    folder: "城市研究期刊",
    issn: ["2226-5856"],
    tags: ["城市管理", "规划治理", "城市政策"],
    description: "聚焦城市管理、规划治理、城市政策和城市发展实践的期刊。",
    includeReason: "城市管理与规划治理研究来源。"
  },
  {
    id: "articulo",
    name: "Articulo - Journal of Urban Research",
    type: "journal",
    region: "欧洲/全球",
    url: "https://journals.openedition.org/articulo/",
    latestUrl: "https://journals.openedition.org/articulo/",
    folder: "城市研究期刊",
    issn: ["1661-4941"],
    tags: ["开放获取", "城市议题", "多语种"],
    description: "开放获取城市研究期刊，发表城市问题相关理论、实证研究和专题论文。",
    includeReason: "开放获取、多语种城市研究来源。"
  }
];

const XIAOHONGSHU_SOURCE_URL = "https://www.xiaohongshu.com/user/profile/5d560a22000000000100976f";

const RESEARCH_MATERIALS = [
  {
    id: "methods-in-urban-analysis",
    title: "一次搞定城市分析方法论 - 城市研究必备手册",
    titleEn: "Methods in Urban Analysis",
    format: "城市分析手册",
    formatEn: "Urban Analysis Handbook",
    image: "assets/research-materials/methods-urban-analysis.png",
    sourceUrl: XIAOHONGSHU_SOURCE_URL,
    downloadUrl: "",
    description: "汇集城市管理、城市研究、规划与政策制定中的方法论知识点，适合作为城市分析入门与项目研究框架参考。",
    descriptionEn: "A methods handbook for urban management, urban research, planning, and policy work, useful for structuring analysis projects.",
    tags: ["城市分析", "方法论", "城市管理", "规划研究"]
  },
  {
    id: "15-minute-city",
    title: "15分钟城市：起源、发展、全球城市实践与趋势",
    titleEn: "The 15-Minute City",
    format: "理论与案例资料",
    formatEn: "Theory and Case Resource",
    image: "assets/research-materials/15-minute-city.png",
    sourceUrl: XIAOHONGSHU_SOURCE_URL,
    downloadUrl: "",
    description: "围绕 Carlos Moreno 的 15 分钟城市概念，梳理其起源、发展脉络、全球城市实践与时间友好型城市趋势。",
    descriptionEn: "A resource on Carlos Moreno's 15-minute city concept, its origins, evolution, global practice, and time-friendly urbanism.",
    tags: ["15分钟城市", "社区", "可持续城市", "城市生活圈"]
  },
  {
    id: "villages-in-the-city",
    title: "华南地区城中村设计指南",
    titleEn: "Villages in the City",
    format: "PDF 分享",
    formatEn: "PDF Resource",
    image: "assets/research-materials/villages-in-city.png",
    sourceUrl: XIAOHONGSHU_SOURCE_URL,
    downloadUrl: "",
    description: "聚焦华南地区非正式住区与城中村空间，提供城中村理解、更新与设计研究的参考资料。",
    descriptionEn: "A guide to South China's informal settlements, useful for understanding, renewal, and design research on urban villages.",
    tags: ["城中村", "非正式住区", "华南城市", "城市更新"]
  },
  {
    id: "designing-streets-for-kids",
    title: "为儿童而设计的街道",
    titleEn: "Designing Streets for Kids",
    format: "PDF 分享",
    formatEn: "PDF Resource",
    image: "assets/research-materials/designing-streets-kids.png",
    sourceUrl: XIAOHONGSHU_SOURCE_URL,
    downloadUrl: "",
    description: "面向儿童友好街道的设计指南，关注安全通学、慢行空间、街道家具、活动空间与包容性交通环境。",
    descriptionEn: "A design guide for child-friendly streets, focused on safer mobility, active travel, street furniture, and inclusive public space.",
    tags: ["儿童友好", "街道设计", "慢行", "公共空间"]
  },
  {
    id: "street-transformations",
    title: "如何实施城市街道改造",
    titleEn: "How to Implement Street Transformations",
    format: "PDF 分享",
    formatEn: "PDF Resource",
    image: "assets/research-materials/street-transformations.png",
    sourceUrl: XIAOHONGSHU_SOURCE_URL,
    downloadUrl: "",
    description: "介绍街道改造从问题识别、临时干预、实施推进到空间转型的路径，适合街道更新与战术城市主义参考。",
    descriptionEn: "A resource on implementing street transformations, from diagnosis and interim interventions to delivery and spatial change.",
    tags: ["街道改造", "战术城市主义", "交通", "公共空间"]
  },
  {
    id: "global-street-design-guide",
    title: "全球街道设计指南",
    titleEn: "Global Street Design Guide",
    format: "PDF 分享",
    formatEn: "PDF Resource",
    image: "assets/research-materials/global-street-design-guide.png",
    sourceUrl: XIAOHONGSHU_SOURCE_URL,
    downloadUrl: "",
    description: "全球街道设计的综合指南，覆盖街道断面、交叉口、慢行系统、公交优先与城市公共空间设计原则。",
    descriptionEn: "A comprehensive global street design guide covering sections, intersections, active mobility, transit priority, and public realm principles.",
    tags: ["街道设计", "全球案例", "交通", "公共空间"]
  }
];

const EXCLUDED_SAMPLES = [
  "Urban Insight：网页开发机构，不是城市研究实验室。",
  "Jacobs、AECOM、MVRDV、OMA、SOM、Arup：偏设计咨询或建筑事务所，不作为研究来源收录。",
  "CityEngine、Unity、Unreal、UrbanCanvas：偏工具或软件产品，不作为研究机构收录。",
  "单篇 ScienceDirect/Amazon Science 论文：保留期刊或机构入口，不收录单篇文章。",
  "课程、招生、招聘、作品集、AI 工具、数据公司营销页：主题相关性不足或不适合作为资讯源。"
];
